// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.cs');

goog.require('Blockly.Msg');

Blockly.Msg["ADD_COMMENT"] = "Přidat komentář";
Blockly.Msg["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "Can't delete the variable '%1' because it's part of the definition of the function '%2'";  // untranslated
Blockly.Msg["CHANGE_VALUE_TITLE"] = "Změnit hodnotu:";
Blockly.Msg["CLEAN_UP"] = "Uspořádat bloky";
Blockly.Msg["COLLAPSE_ALL"] = "Sbalit bloky";
Blockly.Msg["COLLAPSE_BLOCK"] = "Sbalit blok";
Blockly.Msg["COLOUR_BLEND_COLOUR1"] = "barva 1";
Blockly.Msg["COLOUR_BLEND_COLOUR2"] = "barva 2";
Blockly.Msg["COLOUR_BLEND_HELPURL"] = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg["COLOUR_BLEND_RATIO"] = "poměr";
Blockly.Msg["COLOUR_BLEND_TITLE"] = "smíchat";
Blockly.Msg["COLOUR_BLEND_TOOLTIP"] = "Smíchá dvě barvy v daném poměru (0.0–1.0).";
Blockly.Msg["COLOUR_PICKER_HELPURL"] = "https://cs.wikipedia.org/wiki/Barva";
Blockly.Msg["COLOUR_PICKER_TOOLTIP"] = "Vyberte barvu z palety.";
Blockly.Msg["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
Blockly.Msg["COLOUR_RANDOM_TITLE"] = "náhodná barva";
Blockly.Msg["COLOUR_RANDOM_TOOLTIP"] = "Zvolte barvu náhodně.";
Blockly.Msg["COLOUR_RGB_BLUE"] = "modrá";
Blockly.Msg["COLOUR_RGB_GREEN"] = "zelená";
Blockly.Msg["COLOUR_RGB_HELPURL"] = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg["COLOUR_RGB_RED"] = "červená";
Blockly.Msg["COLOUR_RGB_TITLE"] = "obarvěte barvou";
Blockly.Msg["COLOUR_RGB_TOOLTIP"] = "Vytvoř barvu se zadaným množstvím červené, zelené a modré.  Všechny hodnoty musí být mezi 0 a 100.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "vyskočit ze smyčky";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "pokračuj dalším opakováním smyčky";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "Vyskoč z vnitřní smyčky.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "Přeskoč zbytek této smyčky a pokračuj dalším opakováním.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_WARNING"] = "Upozornění: Tento blok může být použit pouze uvnitř smyčky.";
Blockly.Msg["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg["CONTROLS_FOREACH_TITLE"] = "pro každou položku %1 v seznamu %2";
Blockly.Msg["CONTROLS_FOREACH_TOOLTIP"] = "Pro každou položku v seznamu nastavte do proměnné '%1' danou položku a proveďte nějaké operace.";
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "počítat s %1 od %2 do %3 po %4";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "Nechá proměnnou '%1' nabývat hodnot od počátečního do koncového čísla po daném přírůstku a provádí s ní příslušné bloky.";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Přidat podmínku do \"pokud\" bloku.";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "Přidej konečnou podmínku zahrnující ostatní případy do bloku \"pokud\".";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "Přidej, odstraň či uspořádej sekce k přenastavení tohoto bloku \"pokud\".";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "jinak";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "nebo pokud";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "pokud";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "Je-li hodnota pravda, proveď určité příkazy.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "Je-li hodnota pravda, proveď první blok příkazů.  V opačném případě proveď druhý blok příkazů.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "Je-li první hodnota pravdivá, proveď první blok příkazů. V opačném případě, je-li pravdivá druhá hodnota, proveď druhý blok příkazů.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "Je-li první hodnota pravda, proveď první blok příkazů.  Je-li druhá hodnota pravda, proveď druhý blok příkazů.  Pokud žádná hodnota není pravda, proveď poslední blok příkazů.";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://cs.wikipedia.org/wiki/Cyklus_pro";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "dělej";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "opakuj %1 krát";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "Proveď určité příkazy několikrát.";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "opakovat dokud";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "opakovat když";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Dokud je hodnota nepravdivá, prováděj určité příkazy.";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Dokud je hodnota pravdivá, prováděj určité příkazy.";
Blockly.Msg["DELETE_ALL_BLOCKS"] = "Smazat všech %1 bloků?";
Blockly.Msg["DELETE_BLOCK"] = "Smazat blok";
Blockly.Msg["DELETE_VARIABLE"] = "Delete the '%1' variable";  // untranslated
Blockly.Msg["DELETE_VARIABLE_CONFIRMATION"] = "Delete %1 uses of the '%2' variable?";  // untranslated
Blockly.Msg["DELETE_X_BLOCKS"] = "Smazat %1 bloků";
Blockly.Msg["DISABLE_BLOCK"] = "Deaktivovat blok";
Blockly.Msg["DUPLICATE_BLOCK"] = "Duplikovat";
Blockly.Msg["DUPLICATE_COMMENT"] = "Duplicate Comment";  // untranslated
Blockly.Msg["ENABLE_BLOCK"] = "Povolit blok";
Blockly.Msg["EXPAND_ALL"] = "Rozbalit bloky";
Blockly.Msg["EXPAND_BLOCK"] = "Rozbalit blok";
Blockly.Msg["EXTERNAL_INPUTS"] = "vnější vstupy";
Blockly.Msg["HELP"] = "Nápověda";
Blockly.Msg["INLINE_INPUTS"] = "Vložené vstupy";
Blockly.Msg["IOS_CANCEL"] = "Cancel";  // untranslated
Blockly.Msg["IOS_ERROR"] = "Chyba";
Blockly.Msg["IOS_OK"] = "OK";  // untranslated
Blockly.Msg["IOS_PROCEDURES_ADD_INPUT"] = "+ Add Input";  // untranslated
Blockly.Msg["IOS_PROCEDURES_ALLOW_STATEMENTS"] = "Allow statements";  // untranslated
Blockly.Msg["IOS_PROCEDURES_DUPLICATE_INPUTS_ERROR"] = "This function has duplicate inputs.";  // untranslated
Blockly.Msg["IOS_PROCEDURES_INPUTS"] = "vstupy";
Blockly.Msg["IOS_VARIABLES_ADD_BUTTON"] = "Přidat";
Blockly.Msg["IOS_VARIABLES_ADD_VARIABLE"] = "+ Add Variable";  // untranslated
Blockly.Msg["IOS_VARIABLES_DELETE_BUTTON"] = "Smazat";
Blockly.Msg["IOS_VARIABLES_EMPTY_NAME_ERROR"] = "You can't use an empty variable name.";  // untranslated
Blockly.Msg["IOS_VARIABLES_RENAME_BUTTON"] = "Přejmenovat";
Blockly.Msg["IOS_VARIABLES_VARIABLE_NAME"] = "Variable name";  // untranslated
Blockly.Msg["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg["LISTS_CREATE_EMPTY_TITLE"] = "vytvořit prázdný seznam";
Blockly.Msg["LISTS_CREATE_EMPTY_TOOLTIP"] = "Vrátí seznam nulové délky, který neobsahuje žádné datové záznamy";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "seznam";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Přidat, odebrat nebo změnit pořadí oddílů tohoto seznamu bloku.";
Blockly.Msg["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "vytvořit seznam s";
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Přidat položku do seznamu.";
Blockly.Msg["LISTS_CREATE_WITH_TOOLTIP"] = "Vytvoř seznam s libovolným počtem položek.";
Blockly.Msg["LISTS_GET_INDEX_FIRST"] = "první";
Blockly.Msg["LISTS_GET_INDEX_FROM_END"] = "# od konce";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";
Blockly.Msg["LISTS_GET_INDEX_GET"] = "získat";
Blockly.Msg["LISTS_GET_INDEX_GET_REMOVE"] = "získat a odstranit";
Blockly.Msg["LISTS_GET_INDEX_LAST"] = "poslední";
Blockly.Msg["LISTS_GET_INDEX_RANDOM"] = "náhodné";
Blockly.Msg["LISTS_GET_INDEX_REMOVE"] = "odstranit";
Blockly.Msg["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "Vrátí první položku v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "Získá položku z určené pozice v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "Vrátí poslední položku v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "Vrátí náhodnou položku ze seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "Odstraní a vrátí první položku v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "Odstraní a získá položku z určené pozice v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "Odstraní a vrátí poslední položku v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "Odstraní a vrátí náhodnou položku v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "Odstraní první položku v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "Odebere položku na konkrétním místě v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "Odstraní poslední položku v seznamu.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "Odstraní náhodou položku v seznamu.";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_END"] = "do # od konce";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_START"] = "do #";
Blockly.Msg["LISTS_GET_SUBLIST_END_LAST"] = "jako poslední";
Blockly.Msg["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_START_FIRST"] = "získat podseznam od první položky";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_END"] = "získat podseznam od # od konce";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_START"] = "získat podseznam od #";
Blockly.Msg["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_TOOLTIP"] = "Vytvoří kopii určené části seznamu.";
Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 je poslední položka.";
Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 je první položka.";
Blockly.Msg["LISTS_INDEX_OF_FIRST"] = "najít první výskyt položky";
Blockly.Msg["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg["LISTS_INDEX_OF_LAST"] = "najít poslední výskyt položky";
Blockly.Msg["LISTS_INDEX_OF_TOOLTIP"] = "Vrací index prvního/posledního výskytu položky v seznamu. Vrací %1, pokud položka nebyla nalezena.";
Blockly.Msg["LISTS_INLIST"] = "v seznamu";
Blockly.Msg["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg["LISTS_ISEMPTY_TITLE"] = "%1 je prázdné";
Blockly.Msg["LISTS_ISEMPTY_TOOLTIP"] = "Vrátí hodnotu pravda, pokud je seznam prázdný.";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "délka %1";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "Vrací počet položek v seznamu.";
Blockly.Msg["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_REPEAT_TITLE"] = "vytvoř seznam s položkou %1 opakovanou %2 krát";
Blockly.Msg["LISTS_REPEAT_TOOLTIP"] = "Vytváří seznam obsahující danou hodnotu n-krát.";
Blockly.Msg["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";  // untranslated
Blockly.Msg["LISTS_REVERSE_MESSAGE0"] = "reverse %1";  // untranslated
Blockly.Msg["LISTS_REVERSE_TOOLTIP"] = "Reverse a copy of a list.";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_INPUT_TO"] = "jako";
Blockly.Msg["LISTS_SET_INDEX_INSERT"] = "vložit na";
Blockly.Msg["LISTS_SET_INDEX_SET"] = "nastavit";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "Vložit položku na začátek seznamu.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "Vloží položku na určenou pozici v seznamu.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "Připojí položku na konec seznamu.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "Připojí položku náhodně do seznamu.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "Nastaví první položku v seznamu.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "Nastaví položku na konkrétní místo v seznamu.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "Nastaví poslední položku v seznamu.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "Nastaví náhodnou položku v seznamu.";
Blockly.Msg["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg["LISTS_SORT_ORDER_ASCENDING"] = "vzestupně";
Blockly.Msg["LISTS_SORT_ORDER_DESCENDING"] = "sestupně";
Blockly.Msg["LISTS_SORT_TITLE"] = "seřadit %1 %2 %3";
Blockly.Msg["LISTS_SORT_TOOLTIP"] = "Seřadit kopii seznamu.";
Blockly.Msg["LISTS_SORT_TYPE_IGNORECASE"] = "abecedně, na velikosti písmen nezáleží";
Blockly.Msg["LISTS_SORT_TYPE_NUMERIC"] = "číselné";
Blockly.Msg["LISTS_SORT_TYPE_TEXT"] = "abecedně";
Blockly.Msg["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg["LISTS_SPLIT_LIST_FROM_TEXT"] = "udělat z textu seznam";
Blockly.Msg["LISTS_SPLIT_TEXT_FROM_LIST"] = "udělat ze seznamu text";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_JOIN"] = "Spojit seznam textů do jednoho textu, rozdělaného oddělovači.";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_SPLIT"] = "Rozdělit text do seznamu textů, lámání na oddělovačích.";
Blockly.Msg["LISTS_SPLIT_WITH_DELIMITER"] = "s oddělovačem";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "nepravda";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "Vrací pravda nebo nepravda.";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "pravda";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://cs.wikipedia.org/wiki/Nerovnost_(matematika)";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "Vrátí hodnotu pravda, pokud se oba vstupy rovnají jeden druhému.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "Navrátí hodnotu pravda, pokud první vstup je větší než druhý vstup.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "Navrátí hodnotu pravda, pokud je první vstup větší a nebo rovný druhému vstupu.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "Navrátí hodnotu pravda, pokud je první vstup menší než druhý vstup.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "Navrátí hodnotu pravda, pokud je první vstup menší a nebo rovný druhému vstupu.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Vrátí hodnotu pravda, pokud se oba vstupy nerovnají sobě navzájem.";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "ne %1";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "Navrátí hodnotu pravda, pokud je vstup nepravda. Navrátí hodnotu nepravda, pokud je vstup pravda.";
Blockly.Msg["LOGIC_NULL"] = "prázdný";
Blockly.Msg["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg["LOGIC_NULL_TOOLTIP"] = "Vrátí prázdnou hodnotu";
Blockly.Msg["LOGIC_OPERATION_AND"] = "a";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "nebo";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "Vrátí hodnotu pravda, pokud oba dva vstupy jsou pravdivé.";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "Vrátí hodnotu pravda, pokud alespoň jeden ze vstupů má hodnotu pravda.";
Blockly.Msg["LOGIC_TERNARY_CONDITION"] = "test";
Blockly.Msg["LOGIC_TERNARY_HELPURL"] = "https://cs.wikipedia.org/wiki/Ternární operátor (programování)";
Blockly.Msg["LOGIC_TERNARY_IF_FALSE"] = "pokud nepravda";
Blockly.Msg["LOGIC_TERNARY_IF_TRUE"] = "pokud pravda";
Blockly.Msg["LOGIC_TERNARY_TOOLTIP"] = "Zkontroluje podmínku v \"testu\". Když je podmínka pravda, vrátí hodnotu \"pokud pravda\"; v opačném případě vrátí hodnotu \"pokud nepravda\".";
Blockly.Msg["LT_ANY"] = "any";  // untranslated
Blockly.Msg["LT_CATEGORY_EVENTS"] = "Events";  // untranslated
Blockly.Msg["LT_EVENT_ON_DEVICE_DO_ACTIONS"] = "do actions %1";  // untranslated
Blockly.Msg["LT_EVENT_ON_DEVICE_TITLE"] = "Device type: %1%4Event on: %2%5Event type: %3";  // untranslated
Blockly.Msg["LT_EVENT_ON_DEVICE_TT"] = "Event on device.";  // untranslated
Blockly.Msg["LT_OFF"] = "off";  // untranslated
Blockly.Msg["LT_ON"] = "on";  // untranslated
Blockly.Msg["LT_SET_STATE_ON_DEVICE_TITLE"] = "Device type: %1%4Set on: %2%5State: %3";  // untranslated
Blockly.Msg["LT_SET_STATE_ON_DEVICE_TT"] = "Change state on device.";  // untranslated
Blockly.Msg["LT_SWITCH"] = "switch";  // untranslated
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://cs.wikipedia.org/wiki/Aritmetika";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Vrátí součet dvou čísel.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Vrátí podíl dvou čísel.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Vrátí rozdíl dvou čísel.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "Vrátí součin dvou čísel.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Vrátí první číslo umocněné na druhé číslo.";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg["MATH_CHANGE_TITLE"] = "zaměň %1 za %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "Přičti číslo k proměnné '%1'.";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "Vraťte jednu z následujících konstant: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (nekonečno).";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "omez %1 na rozmezí od %2 do %3";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "Omezí číslo tak, aby bylo ve stanovených mezích (včetně).";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";
Blockly.Msg["MATH_IS_DIVISIBLE_BY"] = "je dělitelné číslem";
Blockly.Msg["MATH_IS_EVEN"] = "je sudé";
Blockly.Msg["MATH_IS_NEGATIVE"] = "je záporné";
Blockly.Msg["MATH_IS_ODD"] = "je liché";
Blockly.Msg["MATH_IS_POSITIVE"] = "je kladné";
Blockly.Msg["MATH_IS_PRIME"] = "je prvočíslo";
Blockly.Msg["MATH_IS_TOOLTIP"] = "Kontrola, zda je číslo sudé, liché, prvočíslo, celé, kladné, záporné nebo zda je dělitelné daným číslem. Vrací pravdu nebo nepravdu.";
Blockly.Msg["MATH_IS_WHOLE"] = "je celé";
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://cs.wikipedia.org/wiki/Modul%C3%A1rn%C3%AD_aritmetika";
Blockly.Msg["MATH_MODULO_TITLE"] = "zbytek po dělení %1 ÷ %2";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "Vrátí zbytek po dělení dvou čísel.";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://cs.wikipedia.org/wiki/Číslo";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "Číslo.";
Blockly.Msg["MATH_ONLIST_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_ONLIST_OPERATOR_AVERAGE"] = "průměr v seznamu";
Blockly.Msg["MATH_ONLIST_OPERATOR_MAX"] = "největší v seznamu";
Blockly.Msg["MATH_ONLIST_OPERATOR_MEDIAN"] = "medián v seznamu";
Blockly.Msg["MATH_ONLIST_OPERATOR_MIN"] = "nejmenší v seznamu";
Blockly.Msg["MATH_ONLIST_OPERATOR_MODE"] = "nejčastější ze seznamu";
Blockly.Msg["MATH_ONLIST_OPERATOR_RANDOM"] = "náhodná položka seznamu";
Blockly.Msg["MATH_ONLIST_OPERATOR_STD_DEV"] = "směrodatná odchylka ze seznamu";
Blockly.Msg["MATH_ONLIST_OPERATOR_SUM"] = "suma seznamu";
Blockly.Msg["MATH_ONLIST_TOOLTIP_AVERAGE"] = "Vrátí průměr (aritmetický průměr) číselných hodnot v seznamu.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MAX"] = "Vrátí největší číslo v seznamu.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MEDIAN"] = "Vrátí medián seznamu.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MIN"] = "Vrátí nejmenší číslo v seznamu.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MODE"] = "Vrátí seznam nejčastějších položek seznamu.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_RANDOM"] = "Vrátí náhodnou položku ze seznamu.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_STD_DEV"] = "Vrátí směrodatnou odchylku seznamu.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_SUM"] = "Vrátí součet všech čísel v seznamu.";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";
Blockly.Msg["MATH_RANDOM_FLOAT_HELPURL"] = "https://cs.wikipedia.org/wiki/Gener%C3%A1tor_n%C3%A1hodn%C3%BDch_%C4%8D%C3%ADsel";
Blockly.Msg["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "náhodné číslo mezi 0 (včetně) do 1";
Blockly.Msg["MATH_RANDOM_FLOAT_TOOLTIP"] = "Vrátí náhodné číslo mezi 0,0 (včetně) až 1,0";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://cs.wikipedia.org/wiki/Gener%C3%A1tor_n%C3%A1hodn%C3%BDch_%C4%8D%C3%ADsel";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "náhodné celé číslo od %1 do %2";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "Vrací náhodné celé číslo mezi dvěma určenými mezemi, včetně mezních hodnot.";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "zaokrouhlit";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "zaokrouhlit dolů";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "zaokrouhlit nahoru";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "Zaokrouhlit číslo nahoru nebo dolů.";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://cs.wikipedia.org/wiki/Druhá_odmocnina";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "absolutní hodnota";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "druhá odmocnina";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "Vrátí absolutní hodnotu čísla.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "Vrátí mocninu čísla e.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "Vrátí přirozený logaritmus čísla.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "Vrátí desítkový logaritmus čísla.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "Vrátí zápornou hodnotu čísla.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "Vrátí mocninu čísla 10.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "Vrátí druhou odmocninu čísla.";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";
Blockly.Msg["MATH_TRIG_ASIN"] = "arcsin";
Blockly.Msg["MATH_TRIG_ATAN"] = "arctan";
Blockly.Msg["MATH_TRIG_COS"] = "cos";
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";
Blockly.Msg["MATH_TRIG_TAN"] = "tan";
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "Vrátí arkus kosinus čísla.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "Vrátí arkus sinus čísla.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "Vrátí arkus tangens čísla.";
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "Vrátí kosinus úhlu ve stupních.";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "Vrátí sinus úhlu ve stupních.";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "Vrátí tangens úhlu ve stupních.";
Blockly.Msg["NEW_COLOUR_VARIABLE"] = "Vytvořit barvu proměnné...";
Blockly.Msg["NEW_NUMBER_VARIABLE"] = "Vytvořit číselnou proměnnou...";
Blockly.Msg["NEW_STRING_VARIABLE"] = "Vytvořit řetězcovou proměnnou...";
Blockly.Msg["NEW_VARIABLE"] = "Vytvořte proměnnou...";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "Nový název proměnné:";
Blockly.Msg["NEW_VARIABLE_TYPE_TITLE"] = "Nový typ proměnné:";
Blockly.Msg["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "povolit příkazy";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "s:";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://cs.wikipedia.org/wiki/Podprogram";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Spustí uživatelem definovanou funkci '%1'.";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://cs.wikipedia.org/wiki/Podprogram";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "Spustí uživatelem definovanou funkci '%1' a použije její výstup.";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "s:";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "Vytvořit '%1'";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "Popište tuto funkci...";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://cs.wikipedia.org/w/index.php?title=Funkce_(programování)";
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "proveď něco";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "k provedení";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Vytvořit funkci bez výstupu.";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://cs.wikipedia.org/w/index.php?title=Funkce_(programování)";
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "navrátit";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "Vytvořit funkci s výstupem.";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Upozornění: Tato funkce má duplicitní parametry.";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "Zvýraznit definici funkce";
Blockly.Msg["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg["PROCEDURES_IFRETURN_TOOLTIP"] = "Je-li hodnota pravda, pak vrátí druhou hodnotu.";
Blockly.Msg["PROCEDURES_IFRETURN_WARNING"] = "Varování: Tento blok může být použit pouze uvnitř definici funkce.";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "vstupní jméno:";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "Přidat vstupy do funkce.";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "vstupy";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Přidat, odebrat nebo změnit pořadí vstupů této funkce.";
Blockly.Msg["REDO"] = "Znovu";
Blockly.Msg["REMOVE_COMMENT"] = "Odstranit komentář";
Blockly.Msg["RENAME_VARIABLE"] = "Přejmenovat proměnnou...";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "Přejmenuj všech '%1' proměnných na:";
Blockly.Msg["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_APPEND_TITLE"] = "do %1 přidat text %2";
Blockly.Msg["TEXT_APPEND_TOOLTIP"] = "Přidá určitý text k proměnné '%1'.";
Blockly.Msg["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "na malá písmena";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "na Počáteční Velká Písmena";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "na VELKÁ PÍSMENA";
Blockly.Msg["TEXT_CHANGECASE_TOOLTIP"] = "Vrátí kopii textu s jinou velikostí písmen.";
Blockly.Msg["TEXT_CHARAT_FIRST"] = "získat první písmeno";
Blockly.Msg["TEXT_CHARAT_FROM_END"] = "získat # písmeno od konce";
Blockly.Msg["TEXT_CHARAT_FROM_START"] = "získat písmeno #";
Blockly.Msg["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg["TEXT_CHARAT_LAST"] = "získat poslední písmeno";
Blockly.Msg["TEXT_CHARAT_RANDOM"] = "získat náhodné písmeno";
Blockly.Msg["TEXT_CHARAT_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_CHARAT_TITLE"] = "in text %1 %2";  // untranslated
Blockly.Msg["TEXT_CHARAT_TOOLTIP"] = "Získat písmeno na konkrétní pozici.";
Blockly.Msg["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";  // untranslated
Blockly.Msg["TEXT_COUNT_MESSAGE0"] = "count %1 in %2";  // untranslated
Blockly.Msg["TEXT_COUNT_TOOLTIP"] = "Count how many times some text occurs within some other text.";  // untranslated
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Přidat položku do textu.";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "spojit";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "Přidat, odebrat nebo změnit pořadí oddílů tohoto textového bloku.";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_END"] = "do # písmene od konce";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_START"] = "do písmene #";
Blockly.Msg["TEXT_GET_SUBSTRING_END_LAST"] = "do posledního písmene";
Blockly.Msg["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "v textu";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FIRST"] = "získat podřetězec od prvního písmene";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_END"] = "získat podřetězec od písmene # od konce";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_START"] = "získat podřetězec od písmene #";
Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_TOOLTIP"] = "Získat zadanou část textu.";
Blockly.Msg["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg["TEXT_INDEXOF_OPERATOR_FIRST"] = "najít první výskyt textu";
Blockly.Msg["TEXT_INDEXOF_OPERATOR_LAST"] = "najít poslední výskyt textu";
Blockly.Msg["TEXT_INDEXOF_TITLE"] = "v textu %1 %2 %3";
Blockly.Msg["TEXT_INDEXOF_TOOLTIP"] = "Vrátí index prvního/posledního výskytu prvního textu v druhém textu.  Pokud text není nalezen, vypíše %1.";
Blockly.Msg["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg["TEXT_ISEMPTY_TITLE"] = "%1 je prázdný";
Blockly.Msg["TEXT_ISEMPTY_TOOLTIP"] = "Vrátí pravda pokud je zadaný text prázdný.";
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "vytvořit text s";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "Vytvoří kousek textu spojením libovolného počtu položek.";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "délka %1";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "Vrátí počet písmen (včetně mezer) v zadaném textu.";
Blockly.Msg["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg["TEXT_PRINT_TITLE"] = "tisk %1";
Blockly.Msg["TEXT_PRINT_TOOLTIP"] = "Tisk zadaného textu, čísla nebo jiné hodnoty.";
Blockly.Msg["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"] = "Výzva pro uživatele k zadání čísla.";
Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] = "Výzva pro uživatele k zadání nějakého textu.";
Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"] = "výzva k zadání čísla se zprávou";
Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"] = "výzva k zadání textu se zprávou";
Blockly.Msg["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";  // untranslated
Blockly.Msg["TEXT_REPLACE_MESSAGE0"] = "replace %1 with %2 in %3";  // untranslated
Blockly.Msg["TEXT_REPLACE_TOOLTIP"] = "Replace all occurances of some text within some other text.";  // untranslated
Blockly.Msg["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";  // untranslated
Blockly.Msg["TEXT_REVERSE_MESSAGE0"] = "reverse %1";  // untranslated
Blockly.Msg["TEXT_REVERSE_TOOLTIP"] = "Reverses the order of the characters in the text.";  // untranslated
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://cs.wikipedia.org/wiki/Textov%C3%BD_%C5%99et%C4%9Bzec";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "Písmeno, slovo nebo řádek textu.";
Blockly.Msg["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg["TEXT_TRIM_OPERATOR_BOTH"] = "odstranit mezery z obou stran";
Blockly.Msg["TEXT_TRIM_OPERATOR_LEFT"] = "odstranit mezery z levé strany";
Blockly.Msg["TEXT_TRIM_OPERATOR_RIGHT"] = "odstranit mezery z pravé strany";
Blockly.Msg["TEXT_TRIM_TOOLTIP"] = "Vrátí kopii textu s odstraněnými mezerami z jednoho nebo obou konců.";
Blockly.Msg["TODAY"] = "Dnes";
Blockly.Msg["UNDO"] = "Zpět";
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "položka";
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "Vytvořit \"nastavit %1\"";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "Vrátí hodnotu této proměnné.";
Blockly.Msg["VARIABLES_SET"] = "nastavit %1 na %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "Vytvořit \"získat %1\"";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "Nastaví tuto proměnnou, aby se rovnala vstupu.";
Blockly.Msg["VARIABLE_ALREADY_EXISTS"] = "A variable named '%1' already exists.";  // untranslated
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "Proměnná pojmenovaná jako '%1' již existuje pro jiný typ: '%2'.";
Blockly.Msg["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "Say something...";  // untranslated
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["CONTROLS_FOREACH_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_SET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["TEXT_APPEND_VARIABLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_INDEX_OF_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];

Blockly.Msg["MATH_HUE"] = "230";
Blockly.Msg["LOOPS_HUE"] = "120";
Blockly.Msg["LISTS_HUE"] = "260";
Blockly.Msg["LOGIC_HUE"] = "210";
Blockly.Msg["VARIABLES_HUE"] = "330";
Blockly.Msg["TEXTS_HUE"] = "160";
Blockly.Msg["PROCEDURES_HUE"] = "290";
Blockly.Msg["COLOUR_HUE"] = "20";
Blockly.Msg["VARIABLES_DYNAMIC_HUE"] = "310";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//      Blocky translates         //////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Blockly.Msg["LT_CATEGORY_TYPES"] = "Types";
Blockly.Msg["BLINDS_SELECT"] = "Select action";
Blockly.Msg["BLINDS_SET"] = "Set level";
Blockly.Msg["BLINDS_STOP"] = "Stop";
Blockly.Msg["BLINDS_LEVEL"] = "Level";
Blockly.Msg["LT_CONTROL_BLINDS_TT"] = "Allows to control blinds";
Blockly.Msg["LT_CATEGORY_TEXT"] = "Text";
Blockly.Msg["LT_SECONDS"] = "s";
Blockly.Msg["LT_CATEGORY_AUTOMATION"] = "Automation";
Blockly.Msg["LT_CATEGORY_SENSORS"] = "Sensors";
Blockly.Msg["LT_CATEGORY_STATUS"] = "Devices";
Blockly.Msg["LT_TEXT_SPRINTF_TOOLTIP"] = "sprintf function";
Blockly.Msg["LT_TEXT_SPRINTF_MUTATOR"] = "Mutation";
Blockly.Msg["LT_TEXT_SPRINTF_ONOFF"] = "On/Off";
Blockly.Msg["LT_CATEGORY_LOGIC"] = "Logic";
Blockly.Msg["LT_CATEGORY_CONTROL"] = "Device control";
Blockly.Msg["LT_CATEGORY_DATETIME"] = "Date and time";
Blockly.Msg["LT_CATEGORY_NOTIFICATION"] = "Notification";
Blockly.Msg["LT_SET_STATE_ON_VENTILATION"] = "Ventilation: %1 State: %2";
Blockly.Msg["LT_TEXT_SPRINTF_SENS"] = "Sensor";
Blockly.Msg["LT_TEXT_SPRINTF_DIMMER"] = "Dimmer-lamp";
Blockly.Msg["LT_TEXT_SPRINTF_VARIABLE"] = "Variable";
Blockly.Msg["LT_TEXT_SPRINTF_RGB"] = "RGB-lamp";
Blockly.Msg["LT_TEXT_SPRINTF_CONDITIONER"] = "AC unit";
Blockly.Msg["LT_TEXT_SPRINTF_HEATING"] = "Valve-heating";
Blockly.Msg["LT_TEXT_SPRINTF_FANCOIL"] = "Fancoil";
Blockly.Msg["LT_TEXT_SPRINTF_CC"] = "Climate-control";
Blockly.Msg["LT_TEXT_SPRINTF_VENT"] = "Ventilation";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE"] = "Type";
Blockly.Msg["LT_OTHER_ON"] = "On";
Blockly.Msg["LT_OTHER_OFF"] = "Off";
Blockly.Msg["LT_OTHER_TOGGLE"] = "Toggle";
Blockly.Msg["LT_OTHER_EXTENDED"] = "Extended";
Blockly.Msg["LT_OTHER_POWER"] = "Power";
Blockly.Msg["LT_OTHER_TEMTERATURA"] = "Temperatura";
Blockly.Msg["LT_TEXT_COMPARE"] = "Compare %1 and %2";
Blockly.Msg["LT_STATUS_SET_ON_OFF"] = "Device: %1 turn %2";
Blockly.Msg["LT_OTHER_BYTE"] = "byte";
Blockly.Msg["LT_SIMPLE_EVENT_ON_DEVICE"] = "Script. Auto Off %2 time %3s %4On %1";
Blockly.Msg["LT_SIMPLE_EVENT_ON_DEVICE1"] = "Script. Auto Off";
Blockly.Msg["LT_SIMPLE_EVENT_ON_DEVICE2"] = " time %2s %3On %1";
Blockly.Msg["LT_TEXT_SPRINTF_DEV"] = "Device";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_ONOFF"] = "On/Off";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_BRGHST"] = "Brightness in %";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_COLOR"] = "Color in HEX";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_INTPRT"] = "Integer part";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_FRCT"] = "Fractional part";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_FLT"] = "Float number";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_MODE"] = "Mode";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_TEMP"] = "Temperature";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_CO2"] = "CO2";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_POWER"] = "Power";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_FAN"] = "Fan";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_HB"] = "Horizontal blinds";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_VB"] = "Vertical blinds";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_SENSTEMP"] = "Sensors temperature";
Blockly.Msg["LT_RESET_LEAK_SENSOR"] = "Reset leak sensor %1 after %2 seconds";
Blockly.Msg["LT_OTHER_SENSOR"] = "Sensor";
Blockly.Msg["LT_AUTOMATION_IS_ON_DSCR"] = "Is automation turned on %1";
Blockly.Msg["LT_OTHER_FRATIONAL_PART"] = "Fractional part";
Blockly.Msg["LT_AUTOMATION_IS_DEF_DSCR"] = "Is defined %1";
Blockly.Msg["LT_OTHER_INTEGER_PART"] = "Integer part";
Blockly.Msg["LT_OTHER_DOOR_SENSOR"] = "Door-sensor";
Blockly.Msg["LT_RGB_CONTROL"] = "Rgb: %1 State: %2";
Blockly.Msg["LT_OTHER_COLOUR"] = "Colour";
Blockly.Msg["LT_OTHER_TIME"] = "Time";
Blockly.Msg["LT_OTHER_BRIGHTNESS"] = "Brightness";
Blockly.Msg["LT_IR_SENDER"] = "IR-sender  Custom";
Blockly.Msg["LT_IRT"] = "ir-transmitter";
Blockly.Msg["LT_SELECT_REMOTE_CONTROL"] = "Select remote-control";
Blockly.Msg["LT_IR CUSTOM_COMMAND"] = "IR command: 0x";
Blockly.Msg["LT_IR_REMOTE_COMMAND"] = "Select command";
Blockly.Msg["LT_IR_REMOTE_NO_COMMAND"] = "No commands!";
Blockly.Msg["LT_IR_SENDER_TT"] = "Send ir command from remote-control or custom";Blockly.Msg["LT_NOTIFICATION_TEXTBOX"] = "Virtual %1 send message %2";
Blockly.Msg["LT_CONDITIONER_MODE_COOL"] = "Cool";
Blockly.Msg["LT_CONDITIONER_MODE_DRY"] = "Dry";
Blockly.Msg["LT_CONDITIONER_MODE_FAN"] = "Fan";
Blockly.Msg["LT_CONDITIONER_MODE_HEAT"] = "Heat";
Blockly.Msg["LT_CONDITIONER_MODE_AUTO"] = "Auto";
Blockly.Msg["LT_CONDITIONER_FAN_STRONG"] = "Strong airflow";
Blockly.Msg["LT_CONDITIONER_FAN_EXTRA"] = "Extra strong airflow";
Blockly.Msg["LT_CONDITIONER_FAN_AUTO"] = "Auto";
Blockly.Msg["LT_CONDITIONER_FAN_MEDIUM"] = "Medium airflow";
Blockly.Msg["LT_CONDITIONER_FAN_WEAK"] = "Weak airflow";
Blockly.Msg["LT_OTHER_PUSH"] = "Push";
Blockly.Msg["LT_OTHER_NO_MESSAGE"] = "No message";
Blockly.Msg["LT_CONDITIONER_HV_LEFT"] = "Left";
Blockly.Msg["LT_CONDITIONER_HV_EXLEFT"] = "Extreme left";
Blockly.Msg["LT_CONDITIONER_HV_MIDD"] = "Middle";
Blockly.Msg["LT_CONDITIONER_FAN_LFTRGHT"] = "Both left and right";
Blockly.Msg["LT_CONDITIONER_FAN_RIGHT"] = "Right airflow";
Blockly.Msg["LT_CONDITIONER_FAN_EXRIGHT"] = "Extreme right";
Blockly.Msg["LT_CONDITIONER_FAN_ULTR"] = "Ultra wide";
Blockly.Msg["LT_OTHER_NORMAL"] = "Normal";
Blockly.Msg["LT_CONDITIONER_VV_LEFT"] = "Extreme high";
Blockly.Msg["LT_CONDITIONER_VV_MIDD"] = "High";
Blockly.Msg["LT_CONDITIONER_VV_EXRIGHT"] = "Low";
Blockly.Msg["LT_CONDITIONER_VV_RIGHT"] = "Middle";
Blockly.Msg["LT_CONDITIONER_VV_EXLEFT"] = "Auto";
Blockly.Msg["LT_CONDITIONER_VV_ULTR"] = "Ultra wide";
Blockly.Msg["LT_CONDITIONER_VV_LFTRGHT"] = "Extreme low";
Blockly.Msg["LT_OTHER_INTERCOM"] = "Intercom";
Blockly.Msg["LT_CONDITIONER_HV_LEFT"] = "Left";
Blockly.Msg["LT_CONDITIONER_HV_MIDD"] = "Middle";
Blockly.Msg["LT_CONDITIONER_HV_EXRIGHT"] = "Extreme right";
Blockly.Msg["LT_CONDITIONER_HV_RIGHT"] = "Right airflow";
Blockly.Msg["LT_CONDITIONER_HV_LFTRGHT"] = "Both left and right";
Blockly.Msg["LT_CONDITIONER_HV_EXLEFT"] = "Extreme left";
Blockly.Msg["LT_CONDITIONER_HV_ULTR"] = "Ultra wide";
Blockly.Msg["LT_OTHER_IMPORTANT"] = "Important";
Blockly.Msg["LT_OTHER_CRITICAL"] = "Critical";
Blockly.Msg["LT_LOG_MESSAGE"] = "Message to log %1";
Blockly.Msg["LT_LOG_ERROR"] = "Error to log %1";
Blockly.Msg["LT_CONDITIONER_TOOLTIP"] = "Controls of conditioner";
Blockly.Msg["LT_SPEAKER_CONTROL"] = "Speaker: %1 Act: %2";
Blockly.Msg["LT_CONDITIONER_DSCRP"] = "Conditioner: %1 Act: %2";
Blockly.Msg["LT_TEXT_CONVERTNUMB_TO_TEXT"] = "Number to text %1";
Blockly.Msg["LT_TEXT_CONVERTTEXT_TO_NUMB"] = "Text to number %1";
Blockly.Msg["LT_DATA_GET_TIME"] = "Get %1";
Blockly.Msg["LT_DATA_TIME_SEC"] = "Seconds";
Blockly.Msg["LT_DATA_TIME_MIN"] = "Minutes";
Blockly.Msg["LT_DATA_TIME_HRS"] = "Hours";
Blockly.Msg["LT_DATA_TIME_MSEC"] = "Miliseconds";
Blockly.Msg["LT_DATA_TIME_WDAY"] = "Weak day";
Blockly.Msg["LT_DATA_TIME_YEAR"] = "Year";
Blockly.Msg["LT_DATA_TIME_DAY"] = "Day";
Blockly.Msg["LT_DATA_TIME_MNTH"] = "Mounth";
Blockly.Msg["LT_DATA_MONDAY"] = "Monday";
Blockly.Msg["LT_DATA_MUTATOR"] = "Days of the week";
Blockly.Msg["LT_DATA_TUESDAY"] = "Tuesday";
Blockly.Msg["LT_DATA_WEDNESDAY"] = "Wednesday";
Blockly.Msg["LT_DATA_THURSDAY"] = "Thursday";
Blockly.Msg["LT_DATA_SATURDAY"] = "Saturday";
Blockly.Msg["LT_DATA_SUNDAY"] = "Sunday";
Blockly.Msg["LT_DATA_FRIDAY"] = "Friday";
Blockly.Msg["LT_DATA_TIMEINRANGE"] = "Time in range %1-%2";
Blockly.Msg["LT_DATA_WEEKDAY"] = "Week day:";
Blockly.Msg["LT_OTHER_PLAY"] = "PLAY";
Blockly.Msg["LT_OTHER_PAUSE"] = "PAUSE";
Blockly.Msg["LT_OTHER_MUTE"] = "MUTE";
Blockly.Msg["LT_OTHER_CONTINUE"] = "CONTINUE";
Blockly.Msg["LT_OTHER_SYNC"] = "SYNC";
Blockly.Msg["LT_OTHER_SYNCTODEV"] = "SYNC TWO DEVICES";
Blockly.Msg["LT_OTHER_MOVETODEV"] = "MOVE";
Blockly.Msg["LT_MT_TIME"] = "Time";
Blockly.Msg["LT_MT_VOLUME"] = "Volume";
Blockly.Msg["LT_MT_POSITION"] = "Position";
Blockly.Msg["LT_MT_START_FROM"] = "Start from";
Blockly.Msg["LT_MT_PRIORITY"] = "Priority";
Blockly.Msg["LT_HEATING_DEVICE"] = "Device";
Blockly.Msg["LT_HEATING_MODE"] = "Mode";
Blockly.Msg["LT_HEATING_ACTION"] = "On/Off";
Blockly.Msg["LT_EVENT_TIME_MINUTES"] = "minutes";
Blockly.Msg["LT_EVENT_TIME_PERIOD"] = "Timer. Type:%1 period: %2 %4 %3";
Blockly.Msg["LT_EVENT_TIME_SECONDS"] = "seconds";
Blockly.Msg["LT_OTHER_STOP"] = "STOP";
Blockly.Msg["LT_DIMER_BRIGHTNES"] = "Brightness";
Blockly.Msg["LT_DIMER_MESSAGE"] = "Dimmer: %1 State: %2";
Blockly.Msg["LT_HEATING_MESSAGE"] = "Heating: %1 Temperature: %2";
Blockly.Msg["LT_OTHER_GET"] = "Get";
Blockly.Msg["LT_OTHER_BYTE"] = "Byte";
Blockly.Msg["LT_OTHER_TEMTERATURA"] = "Temperatura";
Blockly.Msg["LT_CATEGORY_COLOUR_AUTOMATION"] = "#006e42";
Blockly.Msg["LT_CATEGORY_COLOUR_TEXT"] = "#006e70";
Blockly.Msg["LT_CATEGORY_COLOUR_TYPES"] = "#00cc00";
Blockly.Msg["LT_CATEGORY_COLOUR_SENSORS"] = "#00cc44";
Blockly.Msg["LT_CATEGORY_COLOUR_STATUS"] = "#5a9c42";
Blockly.Msg["LT_CATEGORY_COLOUR_LOGIC"] = "#a39828";
Blockly.Msg["LT_CATEGORY_COLOUR_CONTROL"] = "#9c6a1e";
Blockly.Msg["LT_CATEGORY_COLOUR_DATETIME"] = "#9e551f";
Blockly.Msg["LT_CATEGORY_COLOUR_NOTIFICATION"] = "#9b3328";
Blockly.Msg["LT_CATEGORY_COLOUR_EVENTS"] = "#941116";
Blockly.Msg["LT_CATEGORY_COLOUR_VARIABLES"] = "#003f72";
Blockly.Msg["LT_CATEGORY_COLOUR_FUNCTIONS"] = "#0d2265";
Blockly.Msg["LT_CATEGORY_COLOUR_LOOP"] = "#3b0d5c";
Blockly.Msg["LT_CATEGORY_COLOUR_MATH"] = "#8cff1a";
Blockly.Msg["LT_CATEGORY_COLOUR_OTHER"] = "#6b085c";
Blockly.Msg["LT_CATEGORY_COLOUR_TEAMPLATES"] = "#B3478F";
Blockly.Msg["LT_PUSH_MUTATOR"] = "Mutator";
Blockly.Msg["LT_SELF_STATUS"] = "Script status";
Blockly.Msg["LT_OTHER_USUAL"] = "Usual";
Blockly.Msg["LT_OPT"] = "Get byte from event";
Blockly.Msg["LT_STATUS_IS_ON"] = "Is on %1 or script %2";
Blockly.Msg["LT_HEATING_TEMP"] = "Temperature";
Blockly.Msg["LT_HEATING_CO2"] = "CO2";
Blockly.Msg["LT_HEATING_POWER"] = "Power";
Blockly.Msg["LT_OTHER_COMENT"] = "Coment";
Blockly.Msg["LT_CATEGORY_VARIABLES"] = "Variables";
Blockly.Msg["LT_CATEGORY_FUNCTIONS"] = "Functions";
Blockly.Msg["LT_CATEGORY_MATH"] = "Math";
Blockly.Msg["LT_CATEGORY_LOOP"] = "Loop";
Blockly.Msg["LT_CATEGORY_OTHER"] = "Other";
//----------------------------------------VARS---------------------------------------------------------------
Blockly.Msg["LT_CATEGORY_VARIABLES_NUMBER"] = "%5Global:%4 number:%1 name:%2 value:%3";
Blockly.Msg["LT_CATEGORY_VARIABLES_NUMBER_TOOLTIP"] = "Create a number variable";
Blockly.Msg["LT_CATEGORY_VARIABLES_ARRAY"] = "%5Global:%4 array type:%1 name:%2 size:%6 value:%3";
Blockly.Msg["LT_CATEGORY_VARIABLES_ARRAY_TOOLTIP"] = "Create a array variable";
Blockly.Msg["LT_CATEGORY_VARIABLES_TEXT"] = "%5Global:%4 max size:%2 text name:%1 value:%3";
Blockly.Msg["LT_CATEGORY_VARIABLES_TEXT_TOOLTIP"] = "Create a text variable";
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER"] = "%2get %1";
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER_TOOLTIP"] = "Get the value of a variable";
Blockly.Msg["LT_CATEGORY_VARIABLES_SETTER"] = "%2set: %1";
Blockly.Msg["LT_CATEGORY_VARIABLES_SETTER_TOOLTIP"] = "Set variable value";
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER_TYPE"] = 'Type:';
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER_INDEX"] = 'Index';
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER_VALUE"] = 'Value:';
Blockly.Msg["LT_CATEGORY_VARIABLES_TYPE_NUMBER"] = "Block to write numbers";
Blockly.Msg["LT_CATEGORY_VARIABLES_TYPE_TEXT"] = "Block for writing text";
//----------------------------------------EVENTS---------------------------------------------------------------
Blockly.Msg["LT_EVENT_ON_DEVICE_TTIMER"] = 'Timer.';
Blockly.Msg["LT_EVENT_ON_DEVICE_TTEVENT"] = 'Event on device.';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE"] = 'Device event. Type:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_DEVICE"] = 'Event on:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION"] = 'Event condition:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_TRUE"] = 'Do actions:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_FALSE"] = 'Else event condition:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_ON"] = 'Active';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_OFF"] = 'Inactive';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_ON_DOOR"] = 'Opened';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_OFF_DOOR"] = 'Closed';
Blockly.Msg["LT_EVENT_DEVICE_CONDITION_SWITCH_FF"] = 'Releasing the key';
Blockly.Msg["LT_EVENT_DEVICE_CONDITION_SWITCH_FD"] = 'Holding the key';
Blockly.Msg["LT_EVENT_DEVICE_CONDITION_SWITCH_FC"] = 'Keystroke';
Blockly.Msg["LT_EVENT_DEVICE_DO_ONCE_IN"] = 'Do once in ';
//----------------------------------------GET------------------------------------------------------------------
Blockly.Msg["LT_CATEGORY_STATUS_DESCRIPTION"] = 'Get:';
//-----------------------------------------MESSANGER-----------------------------------------------------------
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER"] = '%3Send %1 message: %2';
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_TT"] = 'Sending a message by the selected messenger';
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_ADD_DEV"] = "Add device";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_ADD_CAM"] = "Add camera";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_DEV"] = "To device:";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_CAM"] = "Camera:";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_CAM_PICTURE"] = "Picture";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_CAM_VIDEO"] = "Video";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_CAM_VIDEO_TIME"] = 'Video duration in sec:';
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_RECIPIENT"] = "Recipient";
//------------------------------------------CONTROL-----------------------------------------------------------
Blockly.Msg["LT_CATEGORY_CONTROL_DIMMER"] = '%2Dimmer: %1';
Blockly.Msg["LT_CATEGORY_CONTROL_BLINDS"] = '%2Blinds: %1';
Blockly.Msg["LT_CATEGORY_CONTROL_MDEIAPOINT_UUID"] = '%2Mediapoint: UUID %1';
Blockly.Msg["LT_CATEGORY_CONTROL_MDEIAPOINT"] = '%2Mediapoint: %1';
Blockly.Msg["LT_MT_URL"] = 'Url';
Blockly.Msg["LT_MT_SS"] = 'Softstart';
Blockly.Msg["LT_MT_SFP"] = 'Start from position';
Blockly.Msg["LT_CATEGORY_CONTROL_ACTION"] = 'Action';
Blockly.Msg["LT_OTHER_MUTE_UUID"] = 'Mute';
Blockly.Msg['LT_CATEGORY_CONTROL_PLAYLIST'] = 'Playlist';
Blockly.Msg["LT_SONOS_REPEAT"] = "Repeat";
Blockly.Msg["LT_SONOS_REPEATONETIMES"] = "RepeatOne";
Blockly.Msg["LT_SONOS_SHUFFLE"] = "Shuffle";
Blockly.Msg["LT_SONOS_CROSSFADE"] = "Crossfade";
Blockly.Msg["LT_MDEIAPOINT"] = 'Mediapoint';
Blockly.Msg["LT_TEXT_SPRINTF_VENTILATION"] = "Ventilation (Virtual)";
Blockly.Msg["LT_CATEGORY_CONTROL_EXE"] = '%3Select exe script: %1 %2';
Blockly.Msg["LT_CATEGORY_CONTROL_EXE_TT"] = 'Run script from server';
Blockly.Msg["LT_CATEGORY_CONTROL_LEAK"] = '%3Sensor: %1 Action: %2';
Blockly.Msg["LT_CATEGORY_CONTROL_LEAK_TT"] = 'Ignore leakage sensor for set time';
Blockly.Msg["LT_SRDSHT_COLUMN"] = 'column';
Blockly.Msg["LT_SRDSHT_PATH"] = 'Path to spreadsheet';
Blockly.Msg["LT_SRDSHT_DESCR"] = 'Writing data to a spreadsheet';
Blockly.Msg["LT_EMAIL_DESCR"] = 'Send data to email';
Blockly.Msg['LT_SRDSHT_DATE'] = 'Write date'
Blockly.Msg["LT_OTHER_PUSH_MESSAGE"] = "Message";
Blockly.Msg["LT_PUSH_MUTATOR_ID"] = "Application ID";
Blockly.Msg["LT_PUSH_MUTATOR_MODE"] = "Notification mode";
Blockly.Msg["LT_LOG_ERR_MSG"] = "Message";
Blockly.Msg["LT_WEBHOOK"] = "Make webhook";
Blockly.Msg["LT_FUNCTION_NAME"] = "Name";
Blockly.Msg["LT_FUNCTION_CALL"] = "Call";
Blockly.Msg["LT_FUNCTION_DALAY"] = "Delay: %1 Time: %2 %3 Repeat: %4";
Blockly.Msg["LT_FUNCTION_CANCEL"] = "Cancel";
Blockly.Msg["LT_FUNCTION_SECONDS"] = "Seconds";
Blockly.Msg["LT_FUNCTION_MILISECONDS"] = "Miliseconds";
Blockly.Msg["LT_FUNCTION_MINUTES"] = "Minutes";
Blockly.Msg["LT_FUNCTION_DELAYED_CODE"] = "Delayed code: %1 Time: %2 %3 Repeat: %4";
Blockly.Msg["LT_LOOP_HEAD"] = "Repeat %1 times";
Blockly.Msg["LT_LOOP_DO"] = "Do";
Blockly.Msg["LT_LOOP_BREAK"] = "Break";
Blockly.Msg["LT_LOOP_CONTINUE"] = "Continue";
Blockly.Msg["LT_OTHER_MODBUS"] = "ModBus: %1 Send to: %2 Comand: %3 Register: %4";
Blockly.Msg["LT_OTHER_MODBUS_READ"] = "Read";
Blockly.Msg["LT_OTHER_MODBUS_WRITE"] = "Write";
Blockly.Msg["LT_OTHER_MODBUS_ANSWER"] = "Answer";
Blockly.Msg["LT_OTHER_MODBUS_ANSWER_SHOW"] = "Print Answer";
Blockly.Msg["LT_OTHER_MODBUS_PRINT"] = "Print";
Blockly.Msg["LT_OTHER_MODBUS_GET"] = "Get sender";
Blockly.Msg["LT_OTHER_MODBUS_GET_COMAND"] = "Get comand";
Blockly.Msg["LT_OTHER_MODBUS_GET_BYTE"] = "Get byte";
Blockly.Msg["LT_OTHER_FLASH"] = "%1 Cell: %2 Value: %3";
Blockly.Msg["LT_OTHER_FLASH_WRITE"] = "Write";
Blockly.Msg["LT_OTHER_FLASH_READ"] = "Read";
Blockly.Msg["LT_NOTIFICATION_LOG_TT"] = "Outputting a message to the server log";
Blockly.Msg["LT_NOTIFICATION_PUSH_TT"] = "Sending push notification";
Blockly.Msg["LT_NOTIFICATION_BOX_TT"] = "Sending a message in a text field in the application";
Blockly.Msg["LT_CONTROL_RGB_TT"] = "RGB lamp state change";
Blockly.Msg["LT_CONTROL_DIMER_TT"] = "Dimer state change";
Blockly.Msg["LT_CONTROL_MEDIAPOINT_TT"] = "Mediapoint state change";
Blockly.Msg["LT_CONTROL_UUID_TT"] = "The change in the state of the mediato through uuid";
Blockly.Msg["LT_CONTROL_SONOS"] = "Sonos";
Blockly.Msg["LT_CONTROL_SONOS_TT"] = "Sonos control";
Blockly.Msg["LT_CONTROL_HEATING_TT"] = "Heating state change";
Blockly.Msg['LT_CC_TEMP0'] = "Setpoint heat";
Blockly.Msg['LT_CC_TEMP1'] = "Setpoint cool";
Blockly.Msg['LT_CC_HUM0'] = "Setpoint humidify";
Blockly.Msg['LT_CC_HUM1'] = "Setpoint dry";
Blockly.Msg['LT_CC_CO2'] = "Setpoint CO2";
Blockly.Msg['LT_CC_WF'] = "Setpoint watm-floor";
Blockly.Msg['LT_CONTROL_CC_TT'] = "Control of climate-control module";
Blockly.Msg["LT_CONTROL_CONDITIONER_TT"] = "Conditioner state change";
Blockly.Msg["LT_CONTROL_VENTILATION_TT"] = "Changing the state of ventilation";
Blockly.Msg["LT_CONTROL_STATUS_ON_OFF_TT"] = "Turn the device on or off";
Blockly.Msg["LT_DATETIME_TT"] = "Is the time in a given period of time and day of the week";
Blockly.Msg["LT_STATUS_GET_STATUS_TT"] = "Get device status";
//---------------------------------------------ALERTS---------------------------------------------
Blockly.Msg["LT_ERROR_EMPTY_IF_ALLERT"] = "Error! In the if construction there can be no empty conditions!";
Blockly.Msg["LT_ERROR_EMPTY_DEVICE"] = "Error! Device address can not be empty!";
Blockly.Msg["LT_ERROR_EMPTY_VAR"] = "Error! There is no such variable!";
Blockly.Msg["LT_ERROR_SPRDSHT_PATH"] = "Error! Invalid path to spreadsheet!";
Blockly.Msg["LT_ERROR_EMAIL"] = "Error! Incorrect E-Mail Address!";
Blockly.Msg["LT_ERROR_MATH_DIV_ZERO"] = "Error! Division by zero!";
Blockly.Msg["LT_ERROR_EMPTY_PLAYLIST"] = "Error! Playlist can not be empty!";
Blockly.Msg["LT_ERROR_FUNC_SAME_NAME"] = "Error! Function with the same name already exist!";
Blockly.Msg["LT_ERROR_VAR_SAME_NAME"] = "Error! Variable with the same name already exist!";
Blockly.Msg["LT_ERROR_MAX_EXCEED"] = "Error! Maximum number of characters exceeded!";
Blockly.Msg["LT_ERROR_COUNT_NOT_EQUAL"] = "Error! Real devices count is not equal to count devices in text!";
Blockly.Msg["LT_ERROR_INCORR_ARRAY"] = "Error! Incorrect array values!";
Blockly.Msg["LT_ERROR_EQUAL_MASTERS"] = "Error! Same master deivces!";
Blockly.Msg["LT_ERROR_MASTER_USING"] = "Error! The blocks use the device that using in another block as master device!";
//-------------------------------------------Email-------------------------------------------
Blockly.Msg["LT_EMAIL_DSCR"] = "Send mail to";
Blockly.Msg["LT_EMAIL_MSG_DSCR"] = "Message";
Blockly.Msg["LT_EMAIL_MSG_THEME_DSCR"] = "Theme";
//-------------------------------------------Flash-------------------------------------------
Blockly.Msg["LT_OTHER_WORD_FLASH"] = "Flash";
//-------------------------------------------Teamplates--------------------------------------
Blockly.Msg["LT_SECURITY_AREA"] = "Area";
Blockly.Msg["LT_SECURITY_DESCR"] = "Security System";
Blockly.Msg["LT_SECURITY_TIMER_TEXT_DESCR"] = "Timer Start Settings";
Blockly.Msg["LT_SECURITY_TIMER_TEXT"] = "The security system is turned on after";
Blockly.Msg["LT_SECURITY_WARNING_TEXT_DESCR"] = "Warning Settings";
Blockly.Msg["LT_SECURITY_WARNING_TEXT"] = "Warning! Movement in the entrance area";
Blockly.Msg["LT_SECURITY_ON_MSG_TEXT_DESCR"] = "Settings when the security is turned on";
Blockly.Msg["LT_SECURITY_ON_MSG_TEXT"] = "Security Mode Enabled";
Blockly.Msg["LT_SECURITY_OFF_MSG_TEXT_DESCR"] = "Settings when security is disabled";
Blockly.Msg["LT_SECURITY_OFF_MSG_TEXT"] = "Security Mode Disabled";
Blockly.Msg["LT_SECURITY_ERROR_MSG_TEXT_DESCR"] = "Error Settings";
Blockly.Msg["LT_SECURITY_ERROR_MSG_TEXT"] = "Error! Not all areas are empty";
Blockly.Msg["LT_SECURITY_RCOVERY_MSG_TEXT_DESCR"] = "Settings when restoring an area";
Blockly.Msg["LT_SECURITY_RCOVERY_MSG_TEXT"] = "The following areas have been restored";
Blockly.Msg["LT_SECURITY_ALARM_MSG_TEXT_DESCR"] = "Alarm Settings";
Blockly.Msg["LT_SECURITY_ALARM_MSG_TEXT"] = "Alarm! Movement in the field";
Blockly.Msg["LT_SECURITY_RECOVERY_TIME_MSG_TEXT"] = "Recovery Time";
Blockly.Msg["LT_SECURITY_TIMER_TIME_MSG_TEXT"] = "Timer: amount of time in seconds";
Blockly.Msg["LT_MODBUS_CONTROLLER_DESCR"] = "Modbus controller";
Blockly.Msg["LT_MODBUS_CONTROLLER_TOOLTIP"] = "Provides controlling the devices like conditioner or ventilation via modbus protocol";
Blockly.Msg["LT_MODBUS_CONTROLLER_REG"] = "register";
Blockly.Msg["LT_MODBUS_CONTROLLER_ADDR"] = "Address";
Blockly.Msg["LT_MODBUS_CONTROLLER_ON"] = "On";
Blockly.Msg["LT_MODBUS_CONTROLLER_OFF"] = "Off";
Blockly.Msg["LT_MODBUS_CONTROLLER_TMIN"] = "Enter t-min value";
Blockly.Msg["LT_MODBUS_CONTROLLER_OFFS"] = "Enter temperature offset";
Blockly.Msg["LT_MODBUS_CONTROLLER_MODE"] = "Select function";
Blockly.Msg["LT_MODBUS_CONTROLLER_TMODEBD"] = "Binary-decimal";
Blockly.Msg["LT_MODBUS_CONTROLLER_TMODEMT"] = "Multiply by 10";
Blockly.Msg["LT_MODBUS_CONTROLLER_MODEFR"] = "Fahrenheit";
Blockly.Msg["LT_MODBUS_CONTROLLER_MODEDF"] = "Default";
Blockly.Msg["LT_MODBUS_CONTROLLER_ID"] = "ID";
Blockly.Msg["LT_GENERAL"] = "General";
Blockly.Msg["LT_BASIC"] = "Basic";
Blockly.Msg["LT_SETTINGS"] = "Settings";
Blockly.Msg["LT_IMITATION"] = "Presence imitation";
Blockly.Msg["LT_IMITATION_AUTOOFF"] = "Turn off all devices";
Blockly.Msg["LT_IMITATION_BEG"] = "At the beginning";
Blockly.Msg["LT_IMITATION_END"] = "At the ending";
Blockly.Msg["LT_PERIOD"] = "Period";
Blockly.Msg["LT_MOVING_MUSIC"] = "Following music";
Blockly.Msg["LT_SAVE_DEVICE_STATE"] = "Save and restore device status";
Blockly.Msg["LT_RELATED_ACTIONS"] = "Related actions";
Blockly.Msg["LT_MASTER"] = "Master";
Blockly.Msg["LT_SLAVE"] = "Slave";
Blockly.Msg["LT_TEAMPLATES"] = "Templates";
Blockly.Msg["LT_USE_MODBUS_MULTIPLY_COMMAND"] = "Multiple writing";
Blockly.Msg["LT_STRING_SENDER_TT"] = "Status sender";
Blockly.Msg["LT_STRING_SENDER"] = "Status sender";
Blockly.Msg["LT_STRING_DEV"] = "Select device:";
Blockly.Msg["LT_STRING_COMMAND"] = "Input status";
Blockly.Msg["LT_OTHER_WEATHER"] = " Get";
Blockly.Msg["LT_OTHER_WEATHER1"] = "Weather";
Blockly.Msg["LT_OTHER_WEATHER2"] = "Humidity";
Blockly.Msg["LT_OTHER_WEATHER3"] = "Temperature";
Blockly.Msg["LT_OTHER_WEATHER4"] = "Pressure";
Blockly.Msg["LT_OTHER_WEATHER5"] = "Wind";
Blockly.Msg["LT_OTHER_WEATHER6"] = "Wind direction";
Blockly.Msg["LT_OTHER_WEATHER7"] = "Illumination";
Blockly.Msg["LT_OTHER_WEATHER8"] = "Sunrise";
Blockly.Msg["LT_OTHER_WEATHER9"] = "Sunset";
Blockly.Msg["LT_OTHER_WEATHER10"] = "Rain";
Blockly.Msg["LT_OTHER_WEATHER11"] = "Snow";
Blockly.Msg["LT_OTHER_CCGET"] = "Climate control: %1 %2";
Blockly.Msg["LT_OTHER_CCGET1"] = "On/Off";
Blockly.Msg["LT_OTHER_CCGET2"] = "Temperature PID";
Blockly.Msg["LT_OTHER_CCGET3"] = "Humidity PID";
Blockly.Msg["LT_OTHER_CCGET4"] = "CO2 PID";
Blockly.Msg["LT_OTHER_CCGET5"] = "Warm floor PID";
Blockly.Msg["LT_OTHER_CCGET6"] = "Setpoint heat";
Blockly.Msg["LT_OTHER_CCGET7"] = "Setpoint cool";
Blockly.Msg["LT_OTHER_CCGET8"] = "Setpoint humidify";
Blockly.Msg["LT_OTHER_CCGET9"] = "Setpoint dry";
Blockly.Msg["LT_OTHER_CCGET10"] = "Setpoint CO2";
Blockly.Msg["LT_OTHER_CCGET11"] = "Setpoint warm floor";
Blockly.Msg["LT_OTHER_CCGET12"] = "Current temperature";
Blockly.Msg["LT_OTHER_CCGET13"] = "Current humidity";
Blockly.Msg["LT_OTHER_CCGET14"] = "Current CO2 level";
Blockly.Msg["LT_OTHER_CCGET15"] = "Current warm floor temperature";
Blockly.Msg["LT_OTHER_MODBUS_READCOIL"] = "Read Coil";
Blockly.Msg["LT_OTHER_MODBUS_WRITECOIL"] = "Write Coil";