// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.it');

goog.require('Blockly.Msg');

Blockly.Msg["ADD_COMMENT"] = "Aggiungi commento";
Blockly.Msg["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "Non si può cancellare la variabile '%1' perché è parte della definizione della funzione '%2'";
Blockly.Msg["CHANGE_VALUE_TITLE"] = "Modifica valore:";
Blockly.Msg["CLEAN_UP"] = "Pulisci i blocchi";
Blockly.Msg["COLLAPSE_ALL"] = "Comprimi blocchi";
Blockly.Msg["COLLAPSE_BLOCK"] = "Comprimi blocco";
Blockly.Msg["COLOUR_BLEND_COLOUR1"] = "colore 1";
Blockly.Msg["COLOUR_BLEND_COLOUR2"] = "colore 2";
Blockly.Msg["COLOUR_BLEND_HELPURL"] = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg["COLOUR_BLEND_RATIO"] = "rapporto";
Blockly.Msg["COLOUR_BLEND_TITLE"] = "miscela";
Blockly.Msg["COLOUR_BLEND_TOOLTIP"] = "Mescola due colori insieme con un determinato rapporto (0.0 - 1.0).";
Blockly.Msg["COLOUR_PICKER_HELPURL"] = "https://it.wikipedia.org/wiki/Colore";
Blockly.Msg["COLOUR_PICKER_TOOLTIP"] = "Scegli un colore dalla tavolozza.";
Blockly.Msg["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
Blockly.Msg["COLOUR_RANDOM_TITLE"] = "colore casuale";
Blockly.Msg["COLOUR_RANDOM_TOOLTIP"] = "Scegli un colore a caso.";
Blockly.Msg["COLOUR_RGB_BLUE"] = "blu";
Blockly.Msg["COLOUR_RGB_GREEN"] = "verde";
Blockly.Msg["COLOUR_RGB_HELPURL"] = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg["COLOUR_RGB_RED"] = "rosso";
Blockly.Msg["COLOUR_RGB_TITLE"] = "colora con";
Blockly.Msg["COLOUR_RGB_TOOLTIP"] = "Crea un colore con la quantità specificata di rosso, verde e blu. Tutti i valori devono essere compresi tra 0 e 100.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "esce dal ciclo";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "prosegui con la successiva iterazione del ciclo";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "Esce dal ciclo.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "Salta il resto di questo ciclo e prosegue con la successiva iterazione.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_WARNING"] = "Attenzioneː Questo blocco può essere usato solo in un ciclo.";
Blockly.Msg["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg["CONTROLS_FOREACH_TITLE"] = "per ogni elemento %1 nella lista %2";
Blockly.Msg["CONTROLS_FOREACH_TOOLTIP"] = "Per ogni elemento in una lista, imposta la variabile '%1'  pari all'elemento e quindi esegue alcune istruzioni.";
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "conta con %1 da %2 a %3 per %4";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "Fa sì che la variabile '%1' prenda tutti i valori a partire dal numero di partenza fino a quello di arrivo, con passo pari all'intervallo specificato, ed esegue il blocco indicato.";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Aggiungi una condizione al blocco se.";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "Aggiungi una condizione finale pigliatutto al blocco se.";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "Aggiungi, elimina o riordina le sezioni per riconfigurare questo blocco se.";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "altrimenti";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "altrimenti se";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "se";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "Se un valore è vero allora esegue alcune istruzioni.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "Se un valore è vero allora esegue il primo blocco di istruzioni. Altrimenti esegue il secondo blocco di istruzioni.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "Se il primo valore è vero allora esegue un primo blocco di istruzioni. Altrimenti, se il secondo valore è vero, esegue un secondo blocco di istruzioni.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "Se il primo valore è vero allora esegue un primo blocco di istruzioni. Altrimenti, se il secondo valore è vero, esegue un secondo blocco di istruzioni. Se nessuno dei valori è vero esegue l'ultimo blocco di istruzioni.";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://it.wikipedia.org/wiki/Ciclo_for";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "fai";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "ripeti %1 volte";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "Esegue alcune istruzione diverse volte.";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "ripeti fino a che";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "ripeti mentre";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Finché un valore è falso, esegue alcune istruzioni.";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Finché un valore è vero, esegue alcune istruzioni.";
Blockly.Msg["DELETE_ALL_BLOCKS"] = "Cancellare tutti i %1 blocchi?";
Blockly.Msg["DELETE_BLOCK"] = "Cancella blocco";
Blockly.Msg["DELETE_VARIABLE"] = "Cancella la variabile '%1'";
Blockly.Msg["DELETE_VARIABLE_CONFIRMATION"] = "Cancella %1 usi della variabile '%2'?";
Blockly.Msg["DELETE_X_BLOCKS"] = "Cancella %1 blocchi";
Blockly.Msg["DISABLE_BLOCK"] = "Disattiva blocco";
Blockly.Msg["DUPLICATE_BLOCK"] = "Duplica";
Blockly.Msg["DUPLICATE_COMMENT"] = "Duplica commento";
Blockly.Msg["ENABLE_BLOCK"] = "Attiva blocco";
Blockly.Msg["EXPAND_ALL"] = "Espandi blocchi";
Blockly.Msg["EXPAND_BLOCK"] = "Espandi blocco";
Blockly.Msg["EXTERNAL_INPUTS"] = "Ingressi esterni";
Blockly.Msg["HELP"] = "Aiuto";
Blockly.Msg["INLINE_INPUTS"] = "Ingressi in linea";
Blockly.Msg["IOS_CANCEL"] = "Annulla";
Blockly.Msg["IOS_ERROR"] = "Errore";
Blockly.Msg["IOS_OK"] = "OK";
Blockly.Msg["IOS_PROCEDURES_ADD_INPUT"] = "+ Aggiungi input";
Blockly.Msg["IOS_PROCEDURES_ALLOW_STATEMENTS"] = "Consenti dichiarazioni";
Blockly.Msg["IOS_PROCEDURES_DUPLICATE_INPUTS_ERROR"] = "Questa funzione ha entrate duplicate.";
Blockly.Msg["IOS_PROCEDURES_INPUTS"] = "INPUTS";
Blockly.Msg["IOS_VARIABLES_ADD_BUTTON"] = "Aggiungi";
Blockly.Msg["IOS_VARIABLES_ADD_VARIABLE"] = "+ Aggiungi variabile";
Blockly.Msg["IOS_VARIABLES_DELETE_BUTTON"] = "Cancella";
Blockly.Msg["IOS_VARIABLES_EMPTY_NAME_ERROR"] = "Non puoi utilizzare un nome di variabile vuoto.";
Blockly.Msg["IOS_VARIABLES_RENAME_BUTTON"] = "Rinomina";
Blockly.Msg["IOS_VARIABLES_VARIABLE_NAME"] = "Nome variabile";
Blockly.Msg["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg["LISTS_CREATE_EMPTY_TITLE"] = "crea lista vuota";
Blockly.Msg["LISTS_CREATE_EMPTY_TOOLTIP"] = "Restituisce una lista, di lunghezza 0, contenente nessun record di dati";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "lista";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Aggiungi, rimuovi o riordina le sezioni per riconfigurare il blocco lista.";
Blockly.Msg["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "crea lista con";
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Aggiunge un elemento alla lista.";
Blockly.Msg["LISTS_CREATE_WITH_TOOLTIP"] = "Crea una lista con un certo numero di elementi.";
Blockly.Msg["LISTS_GET_INDEX_FIRST"] = "primo";
Blockly.Msg["LISTS_GET_INDEX_FROM_END"] = "# dalla fine";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_GET"] = "prendi";
Blockly.Msg["LISTS_GET_INDEX_GET_REMOVE"] = "prendi e rimuovi";
Blockly.Msg["LISTS_GET_INDEX_LAST"] = "ultimo";
Blockly.Msg["LISTS_GET_INDEX_RANDOM"] = "casuale";
Blockly.Msg["LISTS_GET_INDEX_REMOVE"] = "rimuovi";
Blockly.Msg["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "Restituisce il primo elemento in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "Restituisce l'elemento nella posizione indicata della lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "Restituisce l'ultimo elemento in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "Restituisce un elemento casuale in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "Rimuove e restituisce il primo elemento in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "Rimuove e restituisce l'elemento nella posizione indicata in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "Restituisce e rimuove l'ultimo elemento in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "Restituisce e rimuove un elemento casuale in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "Rimuove il primo elemento in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "Rimuove l'elemento nella posizione indicata in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "Rimuove l'ultimo elemento in una lista.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "Rimuove un elemento casuale in una lista.";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_END"] = "da # dalla fine";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_START"] = "fino a #";
Blockly.Msg["LISTS_GET_SUBLIST_END_LAST"] = "dagli ultimi";
Blockly.Msg["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_START_FIRST"] = "prendi sotto-lista dall'inizio";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_END"] = "prendi sotto-lista da # dalla fine";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_START"] = "prendi sotto-lista da #";
Blockly.Msg["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_TOOLTIP"] = "Crea una copia della porzione specificata di una lista.";
Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 corrisponde all'ultimo elemento.";
Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 corrisponde al primo elemento.";
Blockly.Msg["LISTS_INDEX_OF_FIRST"] = "trova la prima occorrenza dell'elemento";
Blockly.Msg["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg["LISTS_INDEX_OF_LAST"] = "trova l'ultima occorrenza dell'elemento";
Blockly.Msg["LISTS_INDEX_OF_TOOLTIP"] = "Restituisce l'indice della prima/ultima occorrenza dell'elemento nella lista. Restituisce %1 se l'elemento non viene trovato.";
Blockly.Msg["LISTS_INLIST"] = "nella lista";
Blockly.Msg["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg["LISTS_ISEMPTY_TITLE"] = "%1 è vuota";
Blockly.Msg["LISTS_ISEMPTY_TOOLTIP"] = "Restituisce vero se la lista è vuota.";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "lunghezza di %1";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "Restituisce la lunghezza della lista";
Blockly.Msg["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_REPEAT_TITLE"] = "crea una lista con l'elemento %1 ripetuto %2 volte";
Blockly.Msg["LISTS_REPEAT_TOOLTIP"] = "Crea una lista costituita dal valore indicato ripetuto per il numero di volte specificato.";
Blockly.Msg["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";  // untranslated
Blockly.Msg["LISTS_REVERSE_MESSAGE0"] = "inverti %1";
Blockly.Msg["LISTS_REVERSE_TOOLTIP"] = "Inverti una copia di un elenco.";
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_INPUT_TO"] = "come";
Blockly.Msg["LISTS_SET_INDEX_INSERT"] = "inserisci in";
Blockly.Msg["LISTS_SET_INDEX_SET"] = "imposta";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "Inserisci l'elemento all'inizio della lista.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "Inserisci un elemento nella posizione indicata in una lista.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "Aggiungi un elemento alla fine di una lista";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "Inserisce l'elemento casualmente in una lista.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "Imposta il primo elemento in una lista.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "Imposta l'elemento nella posizione indicata di una lista.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "Imposta l'ultimo elemento in una lista.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "Imposta un elemento casuale in una lista.";
Blockly.Msg["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg["LISTS_SORT_ORDER_ASCENDING"] = "crescente";
Blockly.Msg["LISTS_SORT_ORDER_DESCENDING"] = "decrescente";
Blockly.Msg["LISTS_SORT_TITLE"] = "ordinamento %1 %2 %3";
Blockly.Msg["LISTS_SORT_TOOLTIP"] = "Ordina una copia di un elenco.";
Blockly.Msg["LISTS_SORT_TYPE_IGNORECASE"] = "alfabetico, ignorare differenze maiuscole e minuscole";
Blockly.Msg["LISTS_SORT_TYPE_NUMERIC"] = "numerico";
Blockly.Msg["LISTS_SORT_TYPE_TEXT"] = "alfabetico";
Blockly.Msg["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg["LISTS_SPLIT_LIST_FROM_TEXT"] = "crea lista da testo";
Blockly.Msg["LISTS_SPLIT_TEXT_FROM_LIST"] = "crea testo da lista";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_JOIN"] = "Unisci una lista di testi in un unico testo, separato da un delimitatore.";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_SPLIT"] = "Dividi il testo in un elenco di testi, interrompendo ad ogni delimitatore.";
Blockly.Msg["LISTS_SPLIT_WITH_DELIMITER"] = "con delimitatore";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "falso";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "Restituisce vero o falso.";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "vero";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://it.wikipedia.org/wiki/Disuguaglianza";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "Restituisce vero se gli input sono uno uguale all'altro.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "Restituisce vero se il primo input è maggiore o uguale al secondo.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "Restituisce uguale se il primo input è maggiore o uguale al secondo input.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "Restituisce vero se il primo input è minore del secondo.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "Restituisce vero se il primo input è minore o uguale al secondo.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Restituisce vero se gli input non sono uno uguale all'altro.";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "non %1";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "Restituisce vero se l'input è falso. Restituisce falso se l'input è vero.";
Blockly.Msg["LOGIC_NULL"] = "nullo";
Blockly.Msg["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg["LOGIC_NULL_TOOLTIP"] = "Restituisce valore nullo.";
Blockly.Msg["LOGIC_OPERATION_AND"] = "e";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "o";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "Restituisce vero se entrambi gli input sono veri.";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "Restituisce vero se almeno uno degli input è vero.";
Blockly.Msg["LOGIC_TERNARY_CONDITION"] = "test";
Blockly.Msg["LOGIC_TERNARY_HELPURL"] = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
Blockly.Msg["LOGIC_TERNARY_IF_FALSE"] = "se falso";
Blockly.Msg["LOGIC_TERNARY_IF_TRUE"] = "se vero";
Blockly.Msg["LOGIC_TERNARY_TOOLTIP"] = "Verifica la condizione in 'test'. Se questa è vera restituisce il valore 'se vero' altrimenti restituisce il valore 'se falso'.";
Blockly.Msg["LT_ANY"] = "any";  // untranslated
Blockly.Msg["LT_CATEGORY_EVENTS"] = "Events";  // untranslated
Blockly.Msg["LT_EVENT_ON_DEVICE_DO_ACTIONS"] = "do actions %1";  // untranslated
Blockly.Msg["LT_EVENT_ON_DEVICE_TITLE"] = "Device type: %1%4Event on: %2%5Event type: %3";  // untranslated
Blockly.Msg["LT_EVENT_ON_DEVICE_TT"] = "Event on device.";  // untranslated
Blockly.Msg["LT_OFF"] = "off";  // untranslated
Blockly.Msg["LT_ON"] = "on";  // untranslated
Blockly.Msg["LT_SET_STATE_ON_DEVICE_TITLE"] = "Device type: %1%4Set on: %2%5State: %3";  // untranslated
Blockly.Msg["LT_SET_STATE_ON_DEVICE_TT"] = "Change state on device.";  // untranslated
Blockly.Msg["LT_SWITCH"] = "switch";  // untranslated
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://it.wikipedia.org/wiki/Aritmetica";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Restituisce la somma dei due numeri.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Restituisce il quoziente dei due numeri.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Restituisce la differenza dei due numeri.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "Restituisce il prodotto dei due numeri.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Restituisce il primo numero elevato alla potenza del secondo numero.";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://it.wikipedia.org/wiki/Addizione";
Blockly.Msg["MATH_CHANGE_TITLE"] = "cambia %1 di %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "Aggiunge un numero alla variabile '%1'.";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://it.wikipedia.org/wiki/Costante_matematica";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "Restituisce una delle costanti comuniː π (3.141…), e (2.718…), φ (1.618…), radq(2) (1.414…), radq(½) (0.707…) o ∞ (infinito).";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "costringi %1 da %2 a %3";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "Costringe un numero all'interno dei limiti indicati (compresi).";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
Blockly.Msg["MATH_IS_DIVISIBLE_BY"] = "è divisibile per";
Blockly.Msg["MATH_IS_EVEN"] = "è pari";
Blockly.Msg["MATH_IS_NEGATIVE"] = "è negativo";
Blockly.Msg["MATH_IS_ODD"] = "è dispari";
Blockly.Msg["MATH_IS_POSITIVE"] = "è positivo";
Blockly.Msg["MATH_IS_PRIME"] = "è primo";
Blockly.Msg["MATH_IS_TOOLTIP"] = "Verifica se un numero è pari, dispari, primo, intero, positivo, negativo o se è divisibile per un certo numero. Restituisce vero o falso.";
Blockly.Msg["MATH_IS_WHOLE"] = "è intero";
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://it.wikipedia.org/wiki/Resto";
Blockly.Msg["MATH_MODULO_TITLE"] = "resto di %1 ÷ %2";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "Restituisce il resto della divisione di due numeri.";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://it.wikipedia.org/wiki/Numero";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "Un numero.";
Blockly.Msg["MATH_ONLIST_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_ONLIST_OPERATOR_AVERAGE"] = "media della lista";
Blockly.Msg["MATH_ONLIST_OPERATOR_MAX"] = "massimo della lista";
Blockly.Msg["MATH_ONLIST_OPERATOR_MEDIAN"] = "mediana della lista";
Blockly.Msg["MATH_ONLIST_OPERATOR_MIN"] = "minimo della lista";
Blockly.Msg["MATH_ONLIST_OPERATOR_MODE"] = "mode della lista";
Blockly.Msg["MATH_ONLIST_OPERATOR_RANDOM"] = "elemento casuale della lista";
Blockly.Msg["MATH_ONLIST_OPERATOR_STD_DEV"] = "deviazione standard della lista";
Blockly.Msg["MATH_ONLIST_OPERATOR_SUM"] = "somma la lista";
Blockly.Msg["MATH_ONLIST_TOOLTIP_AVERAGE"] = "Restituisce la media (media aritmetica) dei valori numerici nella lista.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MAX"] = "Restituisce il più grande numero della lista.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MEDIAN"] = "Restituisce il valore mediano della lista.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MIN"] = "Restituisce il più piccolo numero della lista.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MODE"] = "Restituisce una lista degli elementi più frequenti nella lista.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_RANDOM"] = "Restituisce un elemento casuale della lista.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_STD_DEV"] = "Restituisce la deviazione standard della lista.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_SUM"] = "Restituisce la somma si tutti i numeri nella lista.";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";  // untranslated
Blockly.Msg["MATH_RANDOM_FLOAT_HELPURL"] = "https://it.wikipedia.org/wiki/Numeri_pseudo-casuali";
Blockly.Msg["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "frazione casuale";
Blockly.Msg["MATH_RANDOM_FLOAT_TOOLTIP"] = "Restituisce una frazione compresa fra 0.0 (incluso) e 1.0 (escluso).";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://it.wikipedia.org/wiki/Numeri_pseudo-casuali";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "intero casuale da %1 a %2";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "Restituisce un numero intero casuale compreso tra i due limiti indicati (inclusi).";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://it.wikipedia.org/wiki/Arrotondamento";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "arrotonda";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "arrotonda verso il basso";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "arrotonda verso l'alto";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "Arrotonda un numero verso l'alto o verso il basso.";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://it.wikipedia.org/wiki/Radice_quadrata";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "assoluto";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "radice quadrata";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "Restituisce il valore assoluto del numero.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "Restituisce e elevato alla potenza del numero.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "Restituisce il logaritmo naturale del numero.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "Restituisce il logaritmo in base 10 del numero.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "Restituisce l'opposto del numero.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "Restituisce 10 elevato alla potenza del numero.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "Restituisce la radice quadrata del numero.";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";  // untranslated
Blockly.Msg["MATH_TRIG_ASIN"] = "asin";  // untranslated
Blockly.Msg["MATH_TRIG_ATAN"] = "atan";  // untranslated
Blockly.Msg["MATH_TRIG_COS"] = "cos";  // untranslated
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://it.wikipedia.org/wiki/Funzione_trigonometrica";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";  // untranslated
Blockly.Msg["MATH_TRIG_TAN"] = "tan";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "Restituisce l'arco-coseno di un numero.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "Restituisce l'arco-seno di un numero.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "Restituisce l'arco-tangente di un numero.";
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "Restituisce il coseno di un angolo espresso in gradi (non radianti).";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "Restituisce il seno di un angolo espresso in gradi (non radianti).";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "Restituisce la tangente di un angolo espresso in gradi (non radianti).";
Blockly.Msg["NEW_COLOUR_VARIABLE"] = "Create colour variable...";  // untranslated
Blockly.Msg["NEW_NUMBER_VARIABLE"] = "Create number variable...";  // untranslated
Blockly.Msg["NEW_STRING_VARIABLE"] = "Create string variable...";  // untranslated
Blockly.Msg["NEW_VARIABLE"] = "Crea variabile...";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "Nome della nuova variabile:";
Blockly.Msg["NEW_VARIABLE_TYPE_TITLE"] = "New variable type:";  // untranslated
Blockly.Msg["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "consenti dichiarazioni";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "conː";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://it.wikipedia.org/wiki/Funzione (informatica)";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Esegue la funzione definita dall'utente '%1'.";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://it.wikipedia.org/wiki/Funzione (informatica)";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "Esegue la funzione definita dall'utente '%1' ed usa il suo output.";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "conː";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "Crea '%1'";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "Descrivi questa funzione...";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "fai qualcosa";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "per";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Crea una funzione senza output.";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "ritorna";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "Crea una funzione con un output.";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Attenzioneː Questa funzione ha parametri duplicati.";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "Evidenzia definizione di funzione";
Blockly.Msg["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg["PROCEDURES_IFRETURN_TOOLTIP"] = "Se un valore è vero allora restituisce un secondo valore.";
Blockly.Msg["PROCEDURES_IFRETURN_WARNING"] = "Attenzioneː Questo blocco può essere usato solo all'interno di una definizione di funzione.";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "nome inputː";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "Aggiungi un input alla funzione.";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "input";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Aggiungi, rimuovi o riordina input alla funzione.";
Blockly.Msg["REDO"] = "Ripeti";
Blockly.Msg["REMOVE_COMMENT"] = "Rimuovi commento";
Blockly.Msg["RENAME_VARIABLE"] = "Rinomina variabile...";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "Rinomina tutte le variabili '%1' in:";
Blockly.Msg["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_APPEND_TITLE"] = "a %1 aggiungi il testo %2";
Blockly.Msg["TEXT_APPEND_TOOLTIP"] = "Aggiunge del testo alla variabile '%1'.";
Blockly.Msg["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "in minuscolo";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "con Iniziali Maiuscole";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "in MAIUSCOLO";
Blockly.Msg["TEXT_CHANGECASE_TOOLTIP"] = "Restituisce una copia del testo in un diverso formato maiuscole/minuscole.";
Blockly.Msg["TEXT_CHARAT_FIRST"] = "prendi la prima lettera";
Blockly.Msg["TEXT_CHARAT_FROM_END"] = "prendi la lettera # dalla fine";
Blockly.Msg["TEXT_CHARAT_FROM_START"] = "prendi la lettera #";
Blockly.Msg["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg["TEXT_CHARAT_LAST"] = "prendi l'ultima lettera";
Blockly.Msg["TEXT_CHARAT_RANDOM"] = "prendi lettera casuale";
Blockly.Msg["TEXT_CHARAT_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_CHARAT_TITLE"] = "nel testo %1 %2";
Blockly.Msg["TEXT_CHARAT_TOOLTIP"] = "Restituisce la lettera nella posizione indicata.";
Blockly.Msg["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";
Blockly.Msg["TEXT_COUNT_MESSAGE0"] = "conta %1 in %2";
Blockly.Msg["TEXT_COUNT_TOOLTIP"] = "Contare quante volte una parte di testo si ripete all'interno di qualche altro testo.";
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Aggiungi un elemento al testo.";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "unisci";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "Aggiungi, rimuovi o riordina le sezioni per riconfigurare questo blocco testo.";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_END"] = "alla lettera # dalla fine";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_START"] = "alla lettera #";
Blockly.Msg["TEXT_GET_SUBSTRING_END_LAST"] = "all'ultima lettera";
Blockly.Msg["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "nel testo";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FIRST"] = "prendi sotto-stringa dalla prima lettera";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_END"] = "prendi sotto-stringa dalla lettera # dalla fine";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_START"] = "prendi sotto-stringa dalla lettera #";
Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_TOOLTIP"] = "Restituisce la porzione di testo indicata.";
Blockly.Msg["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg["TEXT_INDEXOF_OPERATOR_FIRST"] = "trova la prima occorrenza del testo";
Blockly.Msg["TEXT_INDEXOF_OPERATOR_LAST"] = "trova l'ultima occorrenza del testo";
Blockly.Msg["TEXT_INDEXOF_TITLE"] = "nel testo %1 %2 %3";
Blockly.Msg["TEXT_INDEXOF_TOOLTIP"] = "Restituisce l'indice della prima occorrenza del primo testo all'interno del secondo testo. Restituisce %1 se il testo non viene trovato.";
Blockly.Msg["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg["TEXT_ISEMPTY_TITLE"] = "%1 è vuoto";
Blockly.Msg["TEXT_ISEMPTY_TOOLTIP"] = "Restituisce vero se il testo fornito è vuoto.";
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "crea testo con";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "Crea un blocco di testo unendo un certo numero di elementi.";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "lunghezza di %1";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "Restituisce il numero di lettere (inclusi gli spazi) nel testo fornito.";
Blockly.Msg["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg["TEXT_PRINT_TITLE"] = "scrivi %1";
Blockly.Msg["TEXT_PRINT_TOOLTIP"] = "Scrive il testo, numero o altro valore indicato.";
Blockly.Msg["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"] = "Richiedi un numero all'utente.";
Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] = "Richiede del testo da parte dell'utente.";
Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"] = "richiedi numero con messaggio";
Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"] = "richiedi testo con messaggio";
Blockly.Msg["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";
Blockly.Msg["TEXT_REPLACE_MESSAGE0"] = "sostituisci %1 con %2 in %3";
Blockly.Msg["TEXT_REPLACE_TOOLTIP"] = "sostituisci tutte le occorrenze di un certo testo con qualche altro testo.";
Blockly.Msg["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";  // untranslated
Blockly.Msg["TEXT_REVERSE_MESSAGE0"] = "inverti %1";
Blockly.Msg["TEXT_REVERSE_TOOLTIP"] = "Inverte l'ordine dei caratteri nel testo.";
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://it.wikipedia.org/wiki/Stringa_(informatica)";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "Una lettera, una parola o una linea di testo.";
Blockly.Msg["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg["TEXT_TRIM_OPERATOR_BOTH"] = "rimuovi spazi da entrambi gli estremi";
Blockly.Msg["TEXT_TRIM_OPERATOR_LEFT"] = "rimuovi spazi a sinistra";
Blockly.Msg["TEXT_TRIM_OPERATOR_RIGHT"] = "rimuovi spazi a destra";
Blockly.Msg["TEXT_TRIM_TOOLTIP"] = "Restituisce una copia del testo con gli spazi rimossi ad uno o entrambe le estremità.";
Blockly.Msg["TODAY"] = "Oggi";
Blockly.Msg["UNDO"] = "Annulla";
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "elemento";
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "Crea 'imposta %1'";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "Restituisce il valore di una variabile.";
Blockly.Msg["VARIABLES_SET"] = "imposta %1 a %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "Crea 'prendi %1'";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "Imposta questa variabile ad essere pari all'input.";
Blockly.Msg["VARIABLE_ALREADY_EXISTS"] = "Una variabile denominata '%1' esiste già.";
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "Una variabile nominata '%1' esiste già per un'altro tipo: '%2'.";
Blockly.Msg["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "Scrivi qualcosa...";
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["CONTROLS_FOREACH_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_SET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["TEXT_APPEND_VARIABLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_INDEX_OF_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];

Blockly.Msg["MATH_HUE"] = "230";
Blockly.Msg["LOOPS_HUE"] = "120";
Blockly.Msg["LISTS_HUE"] = "260";
Blockly.Msg["LOGIC_HUE"] = "210";
Blockly.Msg["VARIABLES_HUE"] = "330";
Blockly.Msg["TEXTS_HUE"] = "160";
Blockly.Msg["PROCEDURES_HUE"] = "290";
Blockly.Msg["COLOUR_HUE"] = "20";
Blockly.Msg["VARIABLES_DYNAMIC_HUE"] = "310";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//      Blocky translates         //////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Blockly.Msg["LT_CATEGORY_TYPES"] = "Types";
Blockly.Msg["BLINDS_SELECT"] = "Select action";
Blockly.Msg["BLINDS_SET"] = "Set level";
Blockly.Msg["BLINDS_STOP"] = "Stop";
Blockly.Msg["BLINDS_LEVEL"] = "Level";
Blockly.Msg["LT_CONTROL_BLINDS_TT"] = "Allows to control blinds";
Blockly.Msg["LT_CATEGORY_TEXT"] = "Text";
Blockly.Msg["LT_SECONDS"] = "s";
Blockly.Msg["LT_CATEGORY_AUTOMATION"] = "Automation";
Blockly.Msg["LT_CATEGORY_SENSORS"] = "Sensors";
Blockly.Msg["LT_CATEGORY_STATUS"] = "Devices";
Blockly.Msg["LT_TEXT_SPRINTF_TOOLTIP"] = "sprintf function";
Blockly.Msg["LT_TEXT_SPRINTF_MUTATOR"] = "Mutation";
Blockly.Msg["LT_TEXT_SPRINTF_ONOFF"] = "On/Off";
Blockly.Msg["LT_CATEGORY_LOGIC"] = "Logic";
Blockly.Msg["LT_CATEGORY_CONTROL"] = "Device control";
Blockly.Msg["LT_CATEGORY_DATETIME"] = "Date and time";
Blockly.Msg["LT_CATEGORY_NOTIFICATION"] = "Notification";
Blockly.Msg["LT_SET_STATE_ON_VENTILATION"] = "Ventilation: %1 State: %2";
Blockly.Msg["LT_TEXT_SPRINTF_SENS"] = "Sensor";
Blockly.Msg["LT_TEXT_SPRINTF_DIMMER"] = "Dimmer-lamp";
Blockly.Msg["LT_TEXT_SPRINTF_VARIABLE"] = "Variable";
Blockly.Msg["LT_TEXT_SPRINTF_RGB"] = "RGB-lamp";
Blockly.Msg["LT_TEXT_SPRINTF_CONDITIONER"] = "AC unit";
Blockly.Msg["LT_TEXT_SPRINTF_HEATING"] = "Valve-heating";
Blockly.Msg["LT_TEXT_SPRINTF_FANCOIL"] = "Fancoil";
Blockly.Msg["LT_TEXT_SPRINTF_CC"] = "Climate-control";
Blockly.Msg["LT_TEXT_SPRINTF_VENT"] = "Ventilation";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE"] = "Type";
Blockly.Msg["LT_OTHER_ON"] = "On";
Blockly.Msg["LT_OTHER_OFF"] = "Off";
Blockly.Msg["LT_OTHER_TOGGLE"] = "Toggle";
Blockly.Msg["LT_OTHER_EXTENDED"] = "Extended";
Blockly.Msg["LT_OTHER_POWER"] = "Power";
Blockly.Msg["LT_OTHER_TEMTERATURA"] = "Temperatura";
Blockly.Msg["LT_TEXT_COMPARE"] = "Compare %1 and %2";
Blockly.Msg["LT_STATUS_SET_ON_OFF"] = "Device: %1 turn %2";
Blockly.Msg["LT_OTHER_BYTE"] = "byte";
Blockly.Msg["LT_SIMPLE_EVENT_ON_DEVICE"] = "Script. Auto Off %2 time %3s %4On %1";
Blockly.Msg["LT_SIMPLE_EVENT_ON_DEVICE1"] = "Script. Auto Off";
Blockly.Msg["LT_SIMPLE_EVENT_ON_DEVICE2"] = " time %2s %3On %1";
Blockly.Msg["LT_TEXT_SPRINTF_DEV"] = "Device";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_ONOFF"] = "On/Off";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_BRGHST"] = "Brightness in %";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_COLOR"] = "Color in HEX";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_INTPRT"] = "Integer part";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_FRCT"] = "Fractional part";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_FLT"] = "Float number";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_MODE"] = "Mode";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_TEMP"] = "Temperature";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_CO2"] = "CO2";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_POWER"] = "Power";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_FAN"] = "Fan";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_HB"] = "Horizontal blinds";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_VB"] = "Vertical blinds";
Blockly.Msg["LT_TEXT_SPRINTF_TYPE_SENSTEMP"] = "Sensors temperature";
Blockly.Msg["LT_RESET_LEAK_SENSOR"] = "Reset leak sensor %1 after %2 seconds";
Blockly.Msg["LT_OTHER_SENSOR"] = "Sensor";
Blockly.Msg["LT_AUTOMATION_IS_ON_DSCR"] = "Is automation turned on %1";
Blockly.Msg["LT_OTHER_FRATIONAL_PART"] = "Fractional part";
Blockly.Msg["LT_AUTOMATION_IS_DEF_DSCR"] = "Is defined %1";
Blockly.Msg["LT_OTHER_INTEGER_PART"] = "Integer part";
Blockly.Msg["LT_OTHER_DOOR_SENSOR"] = "Door-sensor";
Blockly.Msg["LT_RGB_CONTROL"] = "Rgb: %1 State: %2";
Blockly.Msg["LT_OTHER_COLOUR"] = "Colour";
Blockly.Msg["LT_OTHER_TIME"] = "Time";
Blockly.Msg["LT_OTHER_BRIGHTNESS"] = "Brightness";
Blockly.Msg["LT_IR_SENDER"] = "IR-sender  Custom";
Blockly.Msg["LT_IRT"] = "ir-transmitter";
Blockly.Msg["LT_SELECT_REMOTE_CONTROL"] = "Select remote-control";
Blockly.Msg["LT_IR CUSTOM_COMMAND"] = "IR command: 0x";
Blockly.Msg["LT_IR_REMOTE_COMMAND"] = "Select command";
Blockly.Msg["LT_IR_REMOTE_NO_COMMAND"] = "No commands!";
Blockly.Msg["LT_IR_SENDER_TT"] = "Send ir command from remote-control or custom";Blockly.Msg["LT_NOTIFICATION_TEXTBOX"] = "Virtual %1 send message %2";
Blockly.Msg["LT_CONDITIONER_MODE_COOL"] = "Cool";
Blockly.Msg["LT_CONDITIONER_MODE_DRY"] = "Dry";
Blockly.Msg["LT_CONDITIONER_MODE_FAN"] = "Fan";
Blockly.Msg["LT_CONDITIONER_MODE_HEAT"] = "Heat";
Blockly.Msg["LT_CONDITIONER_MODE_AUTO"] = "Auto";
Blockly.Msg["LT_CONDITIONER_FAN_STRONG"] = "Strong airflow";
Blockly.Msg["LT_CONDITIONER_FAN_EXTRA"] = "Extra strong airflow";
Blockly.Msg["LT_CONDITIONER_FAN_AUTO"] = "Auto";
Blockly.Msg["LT_CONDITIONER_FAN_MEDIUM"] = "Medium airflow";
Blockly.Msg["LT_CONDITIONER_FAN_WEAK"] = "Weak airflow";
Blockly.Msg["LT_OTHER_PUSH"] = "Push";
Blockly.Msg["LT_OTHER_NO_MESSAGE"] = "No message";
Blockly.Msg["LT_CONDITIONER_HV_LEFT"] = "Left";
Blockly.Msg["LT_CONDITIONER_HV_EXLEFT"] = "Extreme left";
Blockly.Msg["LT_CONDITIONER_HV_MIDD"] = "Middle";
Blockly.Msg["LT_CONDITIONER_FAN_LFTRGHT"] = "Both left and right";
Blockly.Msg["LT_CONDITIONER_FAN_RIGHT"] = "Right airflow";
Blockly.Msg["LT_CONDITIONER_FAN_EXRIGHT"] = "Extreme right";
Blockly.Msg["LT_CONDITIONER_FAN_ULTR"] = "Ultra wide";
Blockly.Msg["LT_OTHER_NORMAL"] = "Normal";
Blockly.Msg["LT_CONDITIONER_VV_LEFT"] = "Extreme high";
Blockly.Msg["LT_CONDITIONER_VV_MIDD"] = "High";
Blockly.Msg["LT_CONDITIONER_VV_EXRIGHT"] = "Low";
Blockly.Msg["LT_CONDITIONER_VV_RIGHT"] = "Middle";
Blockly.Msg["LT_CONDITIONER_VV_EXLEFT"] = "Auto";
Blockly.Msg["LT_CONDITIONER_VV_ULTR"] = "Ultra wide";
Blockly.Msg["LT_CONDITIONER_VV_LFTRGHT"] = "Extreme low";
Blockly.Msg["LT_OTHER_INTERCOM"] = "Intercom";
Blockly.Msg["LT_CONDITIONER_HV_LEFT"] = "Left";
Blockly.Msg["LT_CONDITIONER_HV_MIDD"] = "Middle";
Blockly.Msg["LT_CONDITIONER_HV_EXRIGHT"] = "Extreme right";
Blockly.Msg["LT_CONDITIONER_HV_RIGHT"] = "Right airflow";
Blockly.Msg["LT_CONDITIONER_HV_LFTRGHT"] = "Both left and right";
Blockly.Msg["LT_CONDITIONER_HV_EXLEFT"] = "Extreme left";
Blockly.Msg["LT_CONDITIONER_HV_ULTR"] = "Ultra wide";
Blockly.Msg["LT_OTHER_IMPORTANT"] = "Important";
Blockly.Msg["LT_OTHER_CRITICAL"] = "Critical";
Blockly.Msg["LT_LOG_MESSAGE"] = "Message to log %1";
Blockly.Msg["LT_LOG_ERROR"] = "Error to log %1";
Blockly.Msg["LT_CONDITIONER_TOOLTIP"] = "Controls of conditioner";
Blockly.Msg["LT_SPEAKER_CONTROL"] = "Speaker: %1 Act: %2";
Blockly.Msg["LT_CONDITIONER_DSCRP"] = "Conditioner: %1 Act: %2";
Blockly.Msg["LT_TEXT_CONVERTNUMB_TO_TEXT"] = "Number to text %1";
Blockly.Msg["LT_TEXT_CONVERTTEXT_TO_NUMB"] = "Text to number %1";
Blockly.Msg["LT_DATA_GET_TIME"] = "Get %1";
Blockly.Msg["LT_DATA_TIME_SEC"] = "Seconds";
Blockly.Msg["LT_DATA_TIME_MIN"] = "Minutes";
Blockly.Msg["LT_DATA_TIME_HRS"] = "Hours";
Blockly.Msg["LT_DATA_TIME_MSEC"] = "Miliseconds";
Blockly.Msg["LT_DATA_TIME_WDAY"] = "Weak day";
Blockly.Msg["LT_DATA_TIME_YEAR"] = "Year";
Blockly.Msg["LT_DATA_TIME_DAY"] = "Day";
Blockly.Msg["LT_DATA_TIME_MNTH"] = "Mounth";
Blockly.Msg["LT_DATA_MONDAY"] = "Monday";
Blockly.Msg["LT_DATA_MUTATOR"] = "Days of the week";
Blockly.Msg["LT_DATA_TUESDAY"] = "Tuesday";
Blockly.Msg["LT_DATA_WEDNESDAY"] = "Wednesday";
Blockly.Msg["LT_DATA_THURSDAY"] = "Thursday";
Blockly.Msg["LT_DATA_SATURDAY"] = "Saturday";
Blockly.Msg["LT_DATA_SUNDAY"] = "Sunday";
Blockly.Msg["LT_DATA_FRIDAY"] = "Friday";
Blockly.Msg["LT_DATA_TIMEINRANGE"] = "Time in range %1-%2";
Blockly.Msg["LT_DATA_WEEKDAY"] = "Week day:";
Blockly.Msg["LT_OTHER_PLAY"] = "PLAY";
Blockly.Msg["LT_OTHER_PAUSE"] = "PAUSE";
Blockly.Msg["LT_OTHER_MUTE"] = "MUTE";
Blockly.Msg["LT_OTHER_CONTINUE"] = "CONTINUE";
Blockly.Msg["LT_OTHER_SYNC"] = "SYNC";
Blockly.Msg["LT_OTHER_SYNCTODEV"] = "SYNC TWO DEVICES";
Blockly.Msg["LT_OTHER_MOVETODEV"] = "MOVE";
Blockly.Msg["LT_MT_TIME"] = "Time";
Blockly.Msg["LT_MT_VOLUME"] = "Volume";
Blockly.Msg["LT_MT_POSITION"] = "Position";
Blockly.Msg["LT_MT_START_FROM"] = "Start from";
Blockly.Msg["LT_MT_PRIORITY"] = "Priority";
Blockly.Msg["LT_HEATING_DEVICE"] = "Device";
Blockly.Msg["LT_HEATING_MODE"] = "Mode";
Blockly.Msg["LT_HEATING_ACTION"] = "On/Off";
Blockly.Msg["LT_EVENT_TIME_MINUTES"] = "minutes";
Blockly.Msg["LT_EVENT_TIME_PERIOD"] = "Timer. Type:%1 period: %2 %4 %3";
Blockly.Msg["LT_EVENT_TIME_SECONDS"] = "seconds";
Blockly.Msg["LT_OTHER_STOP"] = "STOP";
Blockly.Msg["LT_DIMER_BRIGHTNES"] = "Brightness";
Blockly.Msg["LT_DIMER_MESSAGE"] = "Dimmer: %1 State: %2";
Blockly.Msg["LT_HEATING_MESSAGE"] = "Heating: %1 Temperature: %2";
Blockly.Msg["LT_OTHER_GET"] = "Get";
Blockly.Msg["LT_OTHER_BYTE"] = "Byte";
Blockly.Msg["LT_OTHER_TEMTERATURA"] = "Temperatura";
Blockly.Msg["LT_CATEGORY_COLOUR_AUTOMATION"] = "#006e42";
Blockly.Msg["LT_CATEGORY_COLOUR_TEXT"] = "#006e70";
Blockly.Msg["LT_CATEGORY_COLOUR_TYPES"] = "#00cc00";
Blockly.Msg["LT_CATEGORY_COLOUR_SENSORS"] = "#00cc44";
Blockly.Msg["LT_CATEGORY_COLOUR_STATUS"] = "#5a9c42";
Blockly.Msg["LT_CATEGORY_COLOUR_LOGIC"] = "#a39828";
Blockly.Msg["LT_CATEGORY_COLOUR_CONTROL"] = "#9c6a1e";
Blockly.Msg["LT_CATEGORY_COLOUR_DATETIME"] = "#9e551f";
Blockly.Msg["LT_CATEGORY_COLOUR_NOTIFICATION"] = "#9b3328";
Blockly.Msg["LT_CATEGORY_COLOUR_EVENTS"] = "#941116";
Blockly.Msg["LT_CATEGORY_COLOUR_VARIABLES"] = "#003f72";
Blockly.Msg["LT_CATEGORY_COLOUR_FUNCTIONS"] = "#0d2265";
Blockly.Msg["LT_CATEGORY_COLOUR_LOOP"] = "#3b0d5c";
Blockly.Msg["LT_CATEGORY_COLOUR_MATH"] = "#8cff1a";
Blockly.Msg["LT_CATEGORY_COLOUR_OTHER"] = "#6b085c";
Blockly.Msg["LT_CATEGORY_COLOUR_TEAMPLATES"] = "#B3478F";
Blockly.Msg["LT_PUSH_MUTATOR"] = "Mutator";
Blockly.Msg["LT_SELF_STATUS"] = "Script status";
Blockly.Msg["LT_OTHER_USUAL"] = "Usual";
Blockly.Msg["LT_OPT"] = "Get byte from event";
Blockly.Msg["LT_STATUS_IS_ON"] = "Is on %1 or script %2";
Blockly.Msg["LT_HEATING_TEMP"] = "Temperature";
Blockly.Msg["LT_HEATING_CO2"] = "CO2";
Blockly.Msg["LT_HEATING_POWER"] = "Power";
Blockly.Msg["LT_OTHER_COMENT"] = "Coment";
Blockly.Msg["LT_CATEGORY_VARIABLES"] = "Variables";
Blockly.Msg["LT_CATEGORY_FUNCTIONS"] = "Functions";
Blockly.Msg["LT_CATEGORY_MATH"] = "Math";
Blockly.Msg["LT_CATEGORY_LOOP"] = "Loop";
Blockly.Msg["LT_CATEGORY_OTHER"] = "Other";
//----------------------------------------VARS---------------------------------------------------------------
Blockly.Msg["LT_CATEGORY_VARIABLES_NUMBER"] = "%5Global:%4 number:%1 name:%2 value:%3";
Blockly.Msg["LT_CATEGORY_VARIABLES_NUMBER_TOOLTIP"] = "Create a number variable";
Blockly.Msg["LT_CATEGORY_VARIABLES_ARRAY"] = "%5Global:%4 array type:%1 name:%2 size:%6 value:%3";
Blockly.Msg["LT_CATEGORY_VARIABLES_ARRAY_TOOLTIP"] = "Create a array variable";
Blockly.Msg["LT_CATEGORY_VARIABLES_TEXT"] = "%5Global:%4 max size:%2 text name:%1 value:%3";
Blockly.Msg["LT_CATEGORY_VARIABLES_TEXT_TOOLTIP"] = "Create a text variable";
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER"] = "%2get %1";
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER_TOOLTIP"] = "Get the value of a variable";
Blockly.Msg["LT_CATEGORY_VARIABLES_SETTER"] = "%2set: %1";
Blockly.Msg["LT_CATEGORY_VARIABLES_SETTER_TOOLTIP"] = "Set variable value";
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER_TYPE"] = 'Type:';
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER_INDEX"] = 'Index';
Blockly.Msg["LT_CATEGORY_VARIABLES_GETTER_VALUE"] = 'Value:';
Blockly.Msg["LT_CATEGORY_VARIABLES_TYPE_NUMBER"] = "Block to write numbers";
Blockly.Msg["LT_CATEGORY_VARIABLES_TYPE_TEXT"] = "Block for writing text";
//----------------------------------------EVENTS---------------------------------------------------------------
Blockly.Msg["LT_EVENT_ON_DEVICE_TTIMER"] = 'Timer.';
Blockly.Msg["LT_EVENT_ON_DEVICE_TTEVENT"] = 'Event on device.';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE"] = 'Device event. Type:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_DEVICE"] = 'Event on:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION"] = 'Event condition:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_TRUE"] = 'Do actions:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_FALSE"] = 'Else event condition:';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_ON"] = 'Active';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_OFF"] = 'Inactive';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_ON_DOOR"] = 'Opened';
Blockly.Msg["LT_CATEGORY_EVENTS_EVENT_DEVICE_CONDITION_OFF_DOOR"] = 'Closed';
Blockly.Msg["LT_EVENT_DEVICE_CONDITION_SWITCH_FF"] = 'Releasing the key';
Blockly.Msg["LT_EVENT_DEVICE_CONDITION_SWITCH_FD"] = 'Holding the key';
Blockly.Msg["LT_EVENT_DEVICE_CONDITION_SWITCH_FC"] = 'Keystroke';
Blockly.Msg["LT_EVENT_DEVICE_DO_ONCE_IN"] = 'Do once in ';
//----------------------------------------GET------------------------------------------------------------------
Blockly.Msg["LT_CATEGORY_STATUS_DESCRIPTION"] = 'Get:';
//-----------------------------------------MESSANGER-----------------------------------------------------------
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER"] = '%3Send %1 message: %2';
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_TT"] = 'Sending a message by the selected messenger';
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_ADD_DEV"] = "Add device";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_ADD_CAM"] = "Add camera";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_DEV"] = "To device:";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_CAM"] = "Camera:";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_CAM_PICTURE"] = "Picture";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_CAM_VIDEO"] = "Video";
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_CAM_VIDEO_TIME"] = 'Video duration in sec:';
Blockly.Msg["LT_CATEGORY_NOTIFICATION_MESSANGER_RECIPIENT"] = "Recipient";
//------------------------------------------CONTROL-----------------------------------------------------------
Blockly.Msg["LT_CATEGORY_CONTROL_DIMMER"] = '%2Dimmer: %1';
Blockly.Msg["LT_CATEGORY_CONTROL_BLINDS"] = '%2Blinds: %1';
Blockly.Msg["LT_CATEGORY_CONTROL_MDEIAPOINT_UUID"] = '%2Mediapoint: UUID %1';
Blockly.Msg["LT_CATEGORY_CONTROL_MDEIAPOINT"] = '%2Mediapoint: %1';
Blockly.Msg["LT_MT_URL"] = 'Url';
Blockly.Msg["LT_MT_SS"] = 'Softstart';
Blockly.Msg["LT_MT_SFP"] = 'Start from position';
Blockly.Msg["LT_CATEGORY_CONTROL_ACTION"] = 'Action';
Blockly.Msg["LT_OTHER_MUTE_UUID"] = 'Mute';
Blockly.Msg['LT_CATEGORY_CONTROL_PLAYLIST'] = 'Playlist';
Blockly.Msg["LT_SONOS_REPEAT"] = "Repeat";
Blockly.Msg["LT_SONOS_REPEATONETIMES"] = "RepeatOne";
Blockly.Msg["LT_SONOS_SHUFFLE"] = "Shuffle";
Blockly.Msg["LT_SONOS_CROSSFADE"] = "Crossfade";
Blockly.Msg["LT_MDEIAPOINT"] = 'Mediapoint';
Blockly.Msg["LT_TEXT_SPRINTF_VENTILATION"] = "Ventilation (Virtual)";
Blockly.Msg["LT_CATEGORY_CONTROL_EXE"] = '%3Select exe script: %1 %2';
Blockly.Msg["LT_CATEGORY_CONTROL_EXE_TT"] = 'Run script from server';
Blockly.Msg["LT_CATEGORY_CONTROL_LEAK"] = '%3Sensor: %1 Action: %2';
Blockly.Msg["LT_CATEGORY_CONTROL_LEAK_TT"] = 'Ignore leakage sensor for set time';
Blockly.Msg["LT_SRDSHT_COLUMN"] = 'column';
Blockly.Msg["LT_SRDSHT_PATH"] = 'Path to spreadsheet';
Blockly.Msg["LT_SRDSHT_DESCR"] = 'Writing data to a spreadsheet';
Blockly.Msg["LT_EMAIL_DESCR"] = 'Send data to email';
Blockly.Msg['LT_SRDSHT_DATE'] = 'Write date'
Blockly.Msg["LT_OTHER_PUSH_MESSAGE"] = "Message";
Blockly.Msg["LT_PUSH_MUTATOR_ID"] = "Application ID";
Blockly.Msg["LT_PUSH_MUTATOR_MODE"] = "Notification mode";
Blockly.Msg["LT_LOG_ERR_MSG"] = "Message";
Blockly.Msg["LT_WEBHOOK"] = "Make webhook";
Blockly.Msg["LT_FUNCTION_NAME"] = "Name";
Blockly.Msg["LT_FUNCTION_CALL"] = "Call";
Blockly.Msg["LT_FUNCTION_DALAY"] = "Delay: %1 Time: %2 %3 Repeat: %4";
Blockly.Msg["LT_FUNCTION_CANCEL"] = "Cancel";
Blockly.Msg["LT_FUNCTION_SECONDS"] = "Seconds";
Blockly.Msg["LT_FUNCTION_MILISECONDS"] = "Miliseconds";
Blockly.Msg["LT_FUNCTION_MINUTES"] = "Minutes";
Blockly.Msg["LT_FUNCTION_DELAYED_CODE"] = "Delayed code: %1 Time: %2 %3 Repeat: %4";
Blockly.Msg["LT_LOOP_HEAD"] = "Repeat %1 times";
Blockly.Msg["LT_LOOP_DO"] = "Do";
Blockly.Msg["LT_LOOP_BREAK"] = "Break";
Blockly.Msg["LT_LOOP_CONTINUE"] = "Continue";
Blockly.Msg["LT_OTHER_MODBUS"] = "ModBus: %1 Send to: %2 Comand: %3 Register: %4";
Blockly.Msg["LT_OTHER_MODBUS_READ"] = "Read";
Blockly.Msg["LT_OTHER_MODBUS_WRITE"] = "Write";
Blockly.Msg["LT_OTHER_MODBUS_ANSWER"] = "Answer";
Blockly.Msg["LT_OTHER_MODBUS_ANSWER_SHOW"] = "Print Answer";
Blockly.Msg["LT_OTHER_MODBUS_PRINT"] = "Print";
Blockly.Msg["LT_OTHER_MODBUS_GET"] = "Get sender";
Blockly.Msg["LT_OTHER_MODBUS_GET_COMAND"] = "Get comand";
Blockly.Msg["LT_OTHER_MODBUS_GET_BYTE"] = "Get byte";
Blockly.Msg["LT_OTHER_FLASH"] = "%1 Cell: %2 Value: %3";
Blockly.Msg["LT_OTHER_FLASH_WRITE"] = "Write";
Blockly.Msg["LT_OTHER_FLASH_READ"] = "Read";
Blockly.Msg["LT_NOTIFICATION_LOG_TT"] = "Outputting a message to the server log";
Blockly.Msg["LT_NOTIFICATION_PUSH_TT"] = "Sending push notification";
Blockly.Msg["LT_NOTIFICATION_BOX_TT"] = "Sending a message in a text field in the application";
Blockly.Msg["LT_CONTROL_RGB_TT"] = "RGB lamp state change";
Blockly.Msg["LT_CONTROL_DIMER_TT"] = "Dimer state change";
Blockly.Msg["LT_CONTROL_MEDIAPOINT_TT"] = "Mediapoint state change";
Blockly.Msg["LT_CONTROL_UUID_TT"] = "The change in the state of the mediato through uuid";
Blockly.Msg["LT_CONTROL_SONOS"] = "Sonos";
Blockly.Msg["LT_CONTROL_SONOS_TT"] = "Sonos control";
Blockly.Msg["LT_CONTROL_HEATING_TT"] = "Heating state change";
Blockly.Msg['LT_CC_TEMP0'] = "Setpoint heat";
Blockly.Msg['LT_CC_TEMP1'] = "Setpoint cool";
Blockly.Msg['LT_CC_HUM0'] = "Setpoint humidify";
Blockly.Msg['LT_CC_HUM1'] = "Setpoint dry";
Blockly.Msg['LT_CC_CO2'] = "Setpoint CO2";
Blockly.Msg['LT_CC_WF'] = "Setpoint watm-floor";
Blockly.Msg['LT_CONTROL_CC_TT'] = "Control of climate-control module";
Blockly.Msg["LT_CONTROL_CONDITIONER_TT"] = "Conditioner state change";
Blockly.Msg["LT_CONTROL_VENTILATION_TT"] = "Changing the state of ventilation";
Blockly.Msg["LT_CONTROL_STATUS_ON_OFF_TT"] = "Turn the device on or off";
Blockly.Msg["LT_DATETIME_TT"] = "Is the time in a given period of time and day of the week";
Blockly.Msg["LT_STATUS_GET_STATUS_TT"] = "Get device status";
//---------------------------------------------ALERTS---------------------------------------------
Blockly.Msg["LT_ERROR_EMPTY_IF_ALLERT"] = "Error! In the if construction there can be no empty conditions!";
Blockly.Msg["LT_ERROR_EMPTY_DEVICE"] = "Error! Device address can not be empty!";
Blockly.Msg["LT_ERROR_EMPTY_VAR"] = "Error! There is no such variable!";
Blockly.Msg["LT_ERROR_SPRDSHT_PATH"] = "Error! Invalid path to spreadsheet!";
Blockly.Msg["LT_ERROR_EMAIL"] = "Error! Incorrect E-Mail Address!";
Blockly.Msg["LT_ERROR_MATH_DIV_ZERO"] = "Error! Division by zero!";
Blockly.Msg["LT_ERROR_EMPTY_PLAYLIST"] = "Error! Playlist can not be empty!";
Blockly.Msg["LT_ERROR_FUNC_SAME_NAME"] = "Error! Function with the same name already exist!";
Blockly.Msg["LT_ERROR_VAR_SAME_NAME"] = "Error! Variable with the same name already exist!";
Blockly.Msg["LT_ERROR_MAX_EXCEED"] = "Error! Maximum number of characters exceeded!";
Blockly.Msg["LT_ERROR_COUNT_NOT_EQUAL"] = "Error! Real devices count is not equal to count devices in text!";
Blockly.Msg["LT_ERROR_INCORR_ARRAY"] = "Error! Incorrect array values!";
Blockly.Msg["LT_ERROR_EQUAL_MASTERS"] = "Error! Same master deivces!";
Blockly.Msg["LT_ERROR_MASTER_USING"] = "Error! The blocks use the device that using in another block as master device!";
//-------------------------------------------Email-------------------------------------------
Blockly.Msg["LT_EMAIL_DSCR"] = "Send mail to";
Blockly.Msg["LT_EMAIL_MSG_DSCR"] = "Message";
Blockly.Msg["LT_EMAIL_MSG_THEME_DSCR"] = "Theme";
//-------------------------------------------Flash-------------------------------------------
Blockly.Msg["LT_OTHER_WORD_FLASH"] = "Flash";
//-------------------------------------------Teamplates--------------------------------------
Blockly.Msg["LT_SECURITY_AREA"] = "Area";
Blockly.Msg["LT_SECURITY_DESCR"] = "Security System";
Blockly.Msg["LT_SECURITY_TIMER_TEXT_DESCR"] = "Timer Start Settings";
Blockly.Msg["LT_SECURITY_TIMER_TEXT"] = "The security system is turned on after";
Blockly.Msg["LT_SECURITY_WARNING_TEXT_DESCR"] = "Warning Settings";
Blockly.Msg["LT_SECURITY_WARNING_TEXT"] = "Warning! Movement in the entrance area";
Blockly.Msg["LT_SECURITY_ON_MSG_TEXT_DESCR"] = "Settings when the security is turned on";
Blockly.Msg["LT_SECURITY_ON_MSG_TEXT"] = "Security Mode Enabled";
Blockly.Msg["LT_SECURITY_OFF_MSG_TEXT_DESCR"] = "Settings when security is disabled";
Blockly.Msg["LT_SECURITY_OFF_MSG_TEXT"] = "Security Mode Disabled";
Blockly.Msg["LT_SECURITY_ERROR_MSG_TEXT_DESCR"] = "Error Settings";
Blockly.Msg["LT_SECURITY_ERROR_MSG_TEXT"] = "Error! Not all areas are empty";
Blockly.Msg["LT_SECURITY_RCOVERY_MSG_TEXT_DESCR"] = "Settings when restoring an area";
Blockly.Msg["LT_SECURITY_RCOVERY_MSG_TEXT"] = "The following areas have been restored";
Blockly.Msg["LT_SECURITY_ALARM_MSG_TEXT_DESCR"] = "Alarm Settings";
Blockly.Msg["LT_SECURITY_ALARM_MSG_TEXT"] = "Alarm! Movement in the field";
Blockly.Msg["LT_SECURITY_RECOVERY_TIME_MSG_TEXT"] = "Recovery Time";
Blockly.Msg["LT_SECURITY_TIMER_TIME_MSG_TEXT"] = "Timer: amount of time in seconds";
Blockly.Msg["LT_MODBUS_CONTROLLER_DESCR"] = "Modbus controller";
Blockly.Msg["LT_MODBUS_CONTROLLER_TOOLTIP"] = "Provides controlling the devices like conditioner or ventilation via modbus protocol";
Blockly.Msg["LT_MODBUS_CONTROLLER_REG"] = "register";
Blockly.Msg["LT_MODBUS_CONTROLLER_ADDR"] = "Address";
Blockly.Msg["LT_MODBUS_CONTROLLER_ON"] = "On";
Blockly.Msg["LT_MODBUS_CONTROLLER_OFF"] = "Off";
Blockly.Msg["LT_MODBUS_CONTROLLER_TMIN"] = "Enter t-min value";
Blockly.Msg["LT_MODBUS_CONTROLLER_OFFS"] = "Enter temperature offset";
Blockly.Msg["LT_MODBUS_CONTROLLER_MODE"] = "Select function";
Blockly.Msg["LT_MODBUS_CONTROLLER_TMODEBD"] = "Binary-decimal";
Blockly.Msg["LT_MODBUS_CONTROLLER_TMODEMT"] = "Multiply by 10";
Blockly.Msg["LT_MODBUS_CONTROLLER_MODEFR"] = "Fahrenheit";
Blockly.Msg["LT_MODBUS_CONTROLLER_MODEDF"] = "Default";
Blockly.Msg["LT_MODBUS_CONTROLLER_ID"] = "ID";
Blockly.Msg["LT_GENERAL"] = "General";
Blockly.Msg["LT_BASIC"] = "Basic";
Blockly.Msg["LT_SETTINGS"] = "Settings";
Blockly.Msg["LT_IMITATION"] = "Presence imitation";
Blockly.Msg["LT_IMITATION_AUTOOFF"] = "Turn off all devices";
Blockly.Msg["LT_IMITATION_BEG"] = "At the beginning";
Blockly.Msg["LT_IMITATION_END"] = "At the ending";
Blockly.Msg["LT_PERIOD"] = "Period";
Blockly.Msg["LT_MOVING_MUSIC"] = "Following music";
Blockly.Msg["LT_SAVE_DEVICE_STATE"] = "Save and restore device status";
Blockly.Msg["LT_RELATED_ACTIONS"] = "Related actions";
Blockly.Msg["LT_MASTER"] = "Master";
Blockly.Msg["LT_SLAVE"] = "Slave";
Blockly.Msg["LT_TEAMPLATES"] = "Templates";
Blockly.Msg["LT_USE_MODBUS_MULTIPLY_COMMAND"] = "Multiple writing";
Blockly.Msg["LT_STRING_SENDER_TT"] = "Status sender";
Blockly.Msg["LT_STRING_SENDER"] = "Status sender";
Blockly.Msg["LT_STRING_DEV"] = "Select device:";
Blockly.Msg["LT_STRING_COMMAND"] = "Input status";
Blockly.Msg["LT_OTHER_WEATHER"] = " Get";
Blockly.Msg["LT_OTHER_WEATHER1"] = "Weather";
Blockly.Msg["LT_OTHER_WEATHER2"] = "Humidity";
Blockly.Msg["LT_OTHER_WEATHER3"] = "Temperature";
Blockly.Msg["LT_OTHER_WEATHER4"] = "Pressure";
Blockly.Msg["LT_OTHER_WEATHER5"] = "Wind";
Blockly.Msg["LT_OTHER_WEATHER6"] = "Wind direction";
Blockly.Msg["LT_OTHER_WEATHER7"] = "Illumination";
Blockly.Msg["LT_OTHER_WEATHER8"] = "Sunrise";
Blockly.Msg["LT_OTHER_WEATHER9"] = "Sunset";
Blockly.Msg["LT_OTHER_WEATHER10"] = "Rain";
Blockly.Msg["LT_OTHER_WEATHER11"] = "Snow";
Blockly.Msg["LT_OTHER_CCGET"] = "Climate control: %1 %2";
Blockly.Msg["LT_OTHER_CCGET1"] = "On/Off";
Blockly.Msg["LT_OTHER_CCGET2"] = "Temperature PID";
Blockly.Msg["LT_OTHER_CCGET3"] = "Humidity PID";
Blockly.Msg["LT_OTHER_CCGET4"] = "CO2 PID";
Blockly.Msg["LT_OTHER_CCGET5"] = "Warm floor PID";
Blockly.Msg["LT_OTHER_CCGET6"] = "Setpoint heat";
Blockly.Msg["LT_OTHER_CCGET7"] = "Setpoint cool";
Blockly.Msg["LT_OTHER_CCGET8"] = "Setpoint humidify";
Blockly.Msg["LT_OTHER_CCGET9"] = "Setpoint dry";
Blockly.Msg["LT_OTHER_CCGET10"] = "Setpoint CO2";
Blockly.Msg["LT_OTHER_CCGET11"] = "Setpoint warm floor";
Blockly.Msg["LT_OTHER_CCGET12"] = "Current temperature";
Blockly.Msg["LT_OTHER_CCGET13"] = "Current humidity";
Blockly.Msg["LT_OTHER_CCGET14"] = "Current CO2 level";
Blockly.Msg["LT_OTHER_CCGET15"] = "Current warm floor temperature";
Blockly.Msg["LT_OTHER_MODBUS_READCOIL"] = "Read Coil";
Blockly.Msg["LT_OTHER_MODBUS_WRITECOIL"] = "Write Coil";